### ISSUE TITLE
build a custom Debian installer image?

### ISSUE THREAD

**Issue by fedelibre** [systemd/mkosi#301] opened 2018-12-03 12:11 UTC
Use case: I use mkosi to build a customized Debian image. In `mkosi.postinst` I create a new user called `dev` and set up a few configurations for this user. So far so good for most users.
But a developer complained that he cannot freely choose a few configurations, such as the user name and local time. So I'm just curious to know if there's any way I may build an *installer image*. I see that debootstrap has the `--debian-installer` option...

**Comment by lucasdemarchi** [comment] 2019-01-23 20:18
currently there isn't.  What does the --debian-installer option do?

**Comment by johannbg** [comment] 2019-01-23 23:12
Here we potentially hitting the scalability problem I mentioned on the systemd list and @poettering has not commented on yet on how he had envisioned this.

What scales
mkosi/
mkosi/mkosi.arch
mkosi/mkosi.debian
mkosi/mkosi.fedora
mkosi/mkosi.suse

As far as I can tell you can only have one post install and one mkosi.extra which cannot be used with all four distro, or different development enviroment thus does not scale. 

An alternate approach can be
mkosi
-------> environment
-------------------------> default
-------------------------> build
-------------------------> nspawn
-------------------------> postinstall
-------------------------> cache/
-------------------------> passphrase
------------------------ > secure-boot.cr
-------------------------> secure-boot.key
-----------------------------------------> extra/
-------------------------------------------------> file1
-------------------------------------------------> file2

So you end up with ( short output )
mkosi
-------> arch
----------------> default
----------------> postinstall
----------------> extra
-------------------------> file1
-------------------------> file2

mkosi
-------> TestA
-----------------> default
-----------------> postinstall
-----------------> extra
--------------------------> file1
--------------------------> file2
mkosi
-------> TestB
-----------------> default 
-----------------> postinstall
-----------------> extra
-----------------> file1
-----------------> file2
etc..

probably would have to be implemented with a new -env switch to not break existing setups as in 
mkosi -env arch
mkosi -env fedora 
etc...

And an all switch ( -a ) which would build all environments ( mkosi/directory's ) 

mkosi -env -a would build arch,fedora,test 

And the -env and -a could be extended to nspawn to spawn spesific or all environments

**Comment by DaanDeMeyer** [comment] 2020-08-07 20:36
The config stuff is indeed necessary but irrelevant to this request I think. I think what we need to solve this is a way to run systemd-firstboot in the image which allows configuring the local name and shell and whatnot. I'm closing this as a duplicate of #385. This doesn't include actual users since for that we'd need to add support for configuring a user to systemd-firstboot in systemd itself first.

**Closed by DaanDeMeyer** 2020-08-07 20:36 UTC
