### ISSUE TITLE
Race condition between generating verity partition and writing to disk image.

### ISSUE THREAD

**Issue by fernandolobato** [systemd/mkosi#417] opened 2020-05-05 00:13 UTC
I've been running a lot of builds using mkosi, every once in a while (say 1 in 12) I hit an error during build time inserting the verity partition into an image.

I've spent some time debugging and there seems to be a race condition where sometime it takes a bit for a loop device to appear after creating it. I think it's just a matter of adding a conditional wait right after calling loopsetup.

I can probably contribute the changes once I get some bandwidth, just wanted to track it.

The error manifests in this line:

https://github.com/systemd/mkosi/blob/531f52d4815cd4465ce3be82835ea0edbf005272/mkosi#L2760

**Comment by poettering** [comment] 2020-05-12 15:22
Duplicate of #416.

**Closed by poettering** 2020-05-12 15:22 UTC
