### ISSUE TITLE
Output is not subvolume whilst workspace/../root is

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1694] opened 2023-07-21 12:33 UTC
Seems like BTRFS subvolume output is still broken.

I have the BTRFS `/var/lib/machines/` mounted at `mkosi.workspace` and `mkosi.output` and see that a subvolume is created but isn't snapshotted later - instead a file copy operation is done.
```
 grep subvolume /tmp/mkosi/mkosi.11.log 
‣ + btrfs subvolume create /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpgaj6t1xt/root
Create subvolume '/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpgaj6t1xt/root'
```

```
$ sudo sh -c 'ls -dlatr mkosi.output/debian*'
drwxrwx--- 1 root root   168 Apr 27  2021 mkosi.output/debian-bookworm-amd64_0.1
-rw-rw---- 1 root root    62 Jul 21 13:09 mkosi.output/debian-bookworm-amd64_0.1.nspawn
-rw-r--r-- 1 root root 16674 Jul 21 13:09 mkosi.output/debian-bookworm-amd64_0.1.manifest
lrwxrwxrwx 1 root root    25 Jul 21 13:09 mkosi.output/debian-bookworm-amd64 -> debian-bookworm-amd64_0.1
```

```
$ sudo btrfs subvolume list mkosi.workspace
ID 316 gen 2041 top level 5 path lineage-builder
ID 317 gen 698 top level 316 path lineage-builder/home
ID 318 gen 698 top level 316 path lineage-builder/srv
ID 319 gen 698 top level 316 path lineage-builder/var
ID 320 gen 698 top level 319 path lineage-builder/var/tmp
ID 321 gen 698 top level 319 path lineage-builder/var/lib/machines
ID 479 gen 2442 top level 5 path .mkosi.cache

$ sudo btrfs subvolume list mkosi.output
ID 316 gen 2041 top level 5 path lineage-builder
ID 317 gen 698 top level 316 path lineage-builder/home
ID 318 gen 698 top level 316 path lineage-builder/srv
ID 319 gen 698 top level 316 path lineage-builder/var
ID 320 gen 698 top level 319 path lineage-builder/var/tmp
ID 321 gen 698 top level 319 path lineage-builder/var/lib/machines
ID 479 gen 2442 top level 5 path .mkosi.cache

```

**Comment by DaanDeMeyer** [comment] 2023-07-21 20:15
This is a duplicate of #1569 so closing

**Closed by DaanDeMeyer** 2023-07-21 20:15 UTC
