### ISSUE TITLE
Type=ether doesn't match any interfaces

### ISSUE THREAD

**Issue by gdamjan** [systemd/mkosi#219] opened 2018-01-19 15:12 UTC
mkosi creates the /etc/systemd/network/all-ethernet.network file in the image with the `Type=ether` match. But according to my experience (e1000 driver in qemu, e1000e on my laptop), and the internet:
https://unix.stackexchange.com/questions/416305/get-udev-devtype-of-ethernet-interface 
https://lists.freedesktop.org/archives/systemd-devel/2014-January/015999.html

ethernet devices don't have the DEVTYPE attribute.

so when booted in qemu I don't get any network.

Matching on `Name=en*` should be better.

**Comment by DaanDeMeyer** [comment] 2020-07-04 20:15
Is qemu still not getting an IP address? I tried to reproduce this but everything seems to be working fine. networkd does DHCP on ens3 in the VM and gets assigned an IP address.

**Comment by DaanDeMeyer** [comment] 2020-08-07 23:28
Running `./mkosi -d arch --bootable --password '' --qemu-headless -f qemu -nic user,model=e1000`, logging in and checking `networkctl status ens3`, I see a fully configured network interface with IP address assigned by DHCP. I'm going to close this as not reproducible. If there are other devices without the attribute, we can reopen.

**Closed by DaanDeMeyer** 2020-08-07 23:28 UTC
Labels: arch, bug, needs-reporter-feedback
