### ISSUE TITLE
mkosi failed at installing packages inside deb-based container

### ISSUE THREAD

**Issue by andrew-shelyakov** [systemd/mkosi#245] opened 2018-04-10 16:50 UTC
When i try to build deb-based container with following command:
```shell
mkosi --distribution debian --release stable --format directory --output test
```
This error occurs:
```
...
I: Base system installed successfully.
Reading package lists... Done
Building dependency tree... Done
The following additional packages will be installed:
  libdbus-1-3 libexpat1
Suggested packages:
  default-dbus-session-bus | dbus-session-bus
The following NEW packages will be installed:
  dbus libdbus-1-3 libexpat1 libpam-systemd
0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
Need to get 675 kB of archives.
After this operation, 1759 kB of additional disk space will be used.
Get:1 http://cdn-fastly.deb.debian.org/debian stable/main amd64 libdbus-1-3 amd64 1.10.26-0+deb9u1 [194 kB]
Get:2 http://cdn-fastly.deb.debian.org/debian stable/main amd64 libexpat1 amd64 2.2.0-2+deb9u1 [83.4 kB]
Get:3 http://cdn-fastly.deb.debian.org/debian stable/main amd64 dbus amd64 1.10.26-0+deb9u1 [210 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stable/main amd64 libpam-systemd amd64 232-25+deb9u2 [188 kB]
Fetched 675 kB in 0s (738 kB/s)        
debconf: delaying package configuration, since apt-utils is not installed
dpkg: warning: 'ldconfig' not found in PATH or not executable
dpkg: warning: 'start-stop-daemon' not found in PATH or not executable
dpkg: error: 2 expected programs not found in PATH or not executable
Note: root's PATH should usually contain /usr/local/sbin, /usr/sbin and /sbin
E: Sub-process /usr/bin/dpkg returned an error code (2)
‣ Unmounting Package Cache...
‣ Unmounting Package Cache complete.
Traceback (most recent call last):
  File "/usr/bin/mkosi", line 3605, in <module>
    main()
  File "/usr/bin/mkosi", line 3595, in main
    build_stuff(args)
  File "/usr/bin/mkosi", line 3454, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/bin/mkosi", line 3303, in build_image
    install_distribution(args, workspace.name, run_build_script, cached)
  File "/usr/bin/mkosi", line 1536, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/usr/bin/mkosi", line 1321, in install_debian
    install_debian_or_ubuntu(args, workspace, run_build_script, args.mirror)
  File "/usr/bin/mkosi", line 1316, in install_debian_or_ubuntu
    run_workspace_command(args, workspace, network=True, env={'DEBIAN_FRONTEND': 'noninteractive', 'DEBCONF_NONINTERACTIVE_SEEN': 'true'}, *cmdline)
  File "/usr/bin/mkosi", line 906, in run_workspace_command
    run(cmdline, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemd-nspawn', '--quiet', '--directory=/home/test/.mkosi-_pjkbf62/root', '--uuid=5a6270b315bd4e1cb99140d8c12d66cb', '--machine=mkosi-cedc9b0ca42b4f2fbbf34c430c6eb828', '--as-pid2', '--register=no', '--bind=/home/test/.mkosi-_pjkbf62/var-tmp:/var/tmp', '--bind-ro=/etc/resolv.conf', '--setenv=DEBIAN_FRONTEND=noninteractive', '--setenv=DEBCONF_NONINTERACTIVE_SEEN=true', '--', '/usr/bin/apt-get', '--assume-yes', '--no-install-recommends', 'install', 'dbus', 'libpam-systemd']' returned non-zero exit status 100.
```

**Comment by lucaswerkmeister** [comment] 2018-04-10 19:29
I’d like to understand the problem before merging #246… is it that you’re on a distribution with merged `/usr`, and therefore you don’t have `/bin` and `/sbin` in your `PATH` which Debian needs?

**Comment by fgrsnau** [comment] 2018-04-11 10:29
I think the problem is related to <https://github.com/systemd/systemd/issues/8698>.

The default PATH for systemd-nspawn is different for host distributions having a split bin and ones that have not. As the situation is handled correctly for the split usr case, I believe this is more a bug/inconsistency in systemd-nspawn.

**Comment by andrew-shelyakov** [comment] 2018-04-11 12:16
Yes, @fgrsnau is absolutely right. This problem occurs because default PATH environment variable provided by systemd-nspawn isn't contain `/usr/sbin` and `/sbin` directories which are need for apt.

**Comment by fgrsnau** [comment] 2018-07-16 08:00
As the underlying bug in systemd-nspawn got fixed, I think this issue can be closed.

**Closed** 2018-10-05 23:53 UTC
Labels: bug
