### ISSUE TITLE
Using `RuntimeSize` results in build failure

### ISSUE THREAD

**Issue by paulmenzel** [systemd/mkosi#2598] opened 2024-04-05 16:02 UTC
```
$ git log --no-decorate --oneline -1
88c54bab Merge pull request #2351 from septatrix/feature/oci-output-format
$ more mkosi.local.conf
[Content]
Packages=dbus
         systemd
         udev

[Host]
RuntimeSize=20G
$ rm mkosi.output/debian-sid-mkosi.raw*
$ mkosi -d debian -r sid -t disk -o debian-sid-mkosi
[…]
All done.
‣  Installing grub boot loader for BIOS…
‣  (Fixing ownership of package manager cache directory)
Traceback (most recent call last):
  File "/home/build/src/mkosi/mkosi/run.py", line 58, in uncaught_exception_handler
    yield
  File "/home/build/src/mkosi/mkosi/run.py", line 99, in fork_and_wait
    target(*args, **kwargs)
  File "/home/build/src/mkosi/mkosi/__init__.py", line 4378, in run_build
    build_image(Context(args, config, workspace=workspace, resources=resources))
  File "/home/build/src/mkosi/mkosi/__init__.py", line 3710, in build_image
    finalize_staging(context)
  File "/home/build/src/mkosi/mkosi/__init__.py", line 3466, in finalize_staging
    (context.config.output_dir_or_cwd() / f.name).symlink_to(f.readlink())
  File "/usr/lib/python3.11/pathlib.py", line 1199, in symlink_to
    os.symlink(target, self, target_is_directory)
FileExistsError: [Errno 17] File exists: 'debian-sid-mkosi.raw' -> '/home/build/src/mkosi/mkosi.output/debian-sid-mkosi'
```

[Full log](https://github.com/systemd/mkosi/files/14890640/20240405--mkosi-runtimesize.log)

**Comment by DaanDeMeyer** [comment] 2024-04-05 16:46
I need a full log

**Comment by DaanDeMeyer** [comment] 2024-04-09 10:56
@paulmenzel Please add --debug to the CLI arguments and attach that log

**Comment by paulmenzel** [comment] 2024-04-10 11:42
With commit b603426d, I am unable to reproduce it.

[mkosi-debug-log.txt](https://github.com/systemd/mkosi/files/14931615/mkosi-debug-log.txt)

Judging from the description of `RuntimeSize=`, “disk images are grown to the specified size before they're booted with systemd-nspawn or qemu”, I’d assume the final file size is going to be equal.

```
$ ls -lh mkosi.output/debian-sid-mkosi*
lrwxrwxrwx 1 100000 100000   20 Apr 10 13:10 mkosi.output/debian-sid-mkosi -> debian-sid-mkosi.raw
-rw-rw-r-- 1 build  build   89M Apr 10 13:10 mkosi.output/debian-sid-mkosi.efi
-rw-rw-r-- 1 build  build   73M Apr 10 13:10 mkosi.output/debian-sid-mkosi.initrd
-rw-rw-r-- 1 build  build  3.7G Apr 10 13:10 mkosi.output/debian-sid-mkosi.raw
-rw-rw-r-- 1 build  build   16M Apr 10 13:10 mkosi.output/debian-sid-mkosi.vmlinuz
```

**Comment by DaanDeMeyer** [comment] 2024-04-10 11:44
@paulmenzel I'm 99% sure the issue is not related to `RuntimeSize=`. Anyway, let's close this. Let me know if the issue pops up again.

**Closed by DaanDeMeyer** 2024-04-10 11:44 UTC
Labels: bug
