### ISSUE TITLE
OSError: [Errno 75] Value too large for defined data type

### ISSUE THREAD

**Issue by killermoehre** [systemd/mkosi#2488] opened 2024-03-13 06:00 UTC
Hi,

using current git check out on

Arch Linux x64 on XFS

trying to build `redhat-9` with

`mkosi --distribution rhel-ubi --release 9 build`

I get

```python stacktrace
Traceback (most recent call last):
  File "/home/knizek/development/openstack-ironic-images/.venv/lib/python3.11/site-packages/mkosi/run.py", line 55, in uncaught_exception_handler
    yield
  File "/home/knizek/development/openstack-ironic-images/.venv/lib/python3.11/site-packages/mkosi/run.py", line 96, in fork_and_wait
    target(*args, **kwargs)
  File "/home/knizek/development/openstack-ironic-images/.venv/lib/python3.11/site-packages/mkosi/__init__.py", line 4004, in run_build
    with (
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/knizek/development/openstack-ironic-images/.venv/lib/python3.11/site-packages/mkosi/__init__.py", line 3230, in setup_workspace
    workspace = Path(tempfile.mkdtemp(dir=config.workspace_dir_or_default(), prefix="mkosi-workspace"))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 385, in mkdtemp
    _os.mkdir(file, 0o700)
OSError: [Errno 75] Value too large for defined data type: '/home/knizek/.cache/mkosi/mkosi-workspacelizm1ka2'
```

If I try a simple

```python
from pathlib import Path
from tempfile import mkdtemp
tempdir = Path(mkdtemp(dir="/home/knizek/.cache/mkosi"))
tempdir.rmdir()
```

everything works as expected.

Is this an issue with my system itself, the way bubblewrap works or something completely different?

**Comment by DaanDeMeyer** [comment] 2024-03-13 12:19
Are you using systemd-homed or anything like that? And does the problem still occur if you run mkosi as root?

**Comment by killermoehre** [comment] 2024-03-13 14:08
@DaanDeMeyer I use `systemd-homed`, it does not happen if I run `mkosi` as root.

**Comment by DaanDeMeyer** [comment] 2024-03-13 14:17
@killermoehre You're running into https://github.com/systemd/systemd/issues/29297. Make sure your /etc/subuid and /etc/subgid files use a range in the container uid range (https://systemd.io/UIDS-GIDS/).

Closing as this is not a bug in mkosi

**Closed by DaanDeMeyer** 2024-03-13 14:17 UTC
Labels: bug
