### ISSUE TITLE
OpenSuse fails: Failed to cache repo

### ISSUE THREAD

**Issue by Nudin** [systemd/mkosi#159] opened 2017-10-01 00:36 UTC
Building an OpenSuse-Image (on Arch) fails with:
```
Download (curl) error for 'https://download.opensuse.org/update/tumbleweed/repodata/repomd.xml':
Error code:  Bad URL
Error message: Protocol "http" not supported or disabled in libcurl
```
This can be fixed by overriding mirror to not use https but http. (See also #109 & #137) but it still fails then with:

```
Building repository 'Main' cache ................................................................................[done]
Error building the cache:
[|] Failed to cache repo (4).                                                                                          
Warning: The metadata cache needs to be built for the 'Main' repository. You can run 'zypper refresh' as root to do this.
Disabling repository 'Main'.
Building repository 'Updates' cache .............................................................................[done]
Error building the cache:
[|] Failed to cache repo (127).                                                                                        
Warning: The metadata cache needs to be built for the 'Updates' repository. You can run 'zypper refresh' as root to do this.
Disabling repository 'Updates'.
Some of the repositories have not been refreshed because of an error.
Loading repository data...
Reading installed packages...
'patterns-base-minimal_base' not found in package names. Trying capabilities.
No provider of 'patterns-base-minimal_base' found.
```

**Comment by poettering** [comment] 2017-10-10 09:43
Hmm, @fbuihuu is our OpenSuse guru. @fbuihuu any idea what is going on here?

**Comment by fbuihuu** [comment] 2017-10-12 15:01
> Hmm, @fbuihuu is our OpenSuse guru

Oh hum... not really ;)

It looks a duplicate of issue #137

**Comment by Nudin** [comment] 2017-10-12 21:44
Hi,

but if this is only a duplicate of #137 shouldn't it be fixed by  #173? But as mentioned above, I did try that and it removed the first error-message but the second one still happened…

**Comment by lucaswerkmeister** [comment] 2017-10-12 21:52
Hm, I’m also seeing this error.
```
Building repository 'Updates' cache ............[done]
Error building the cache:
[|] Failed to cache repo (127).
Warning: The metadata cache needs to be built for the 'Updates' repository. You can run 'zypper refresh' as root to do this.
Disabling repository 'Updates'.
Some of the repositories have not been refreshed because of an error.
Loading repository data...
Reading installed packages...
'minimal_base' not found in package names. Trying capabilities.
No provider of 'minimal_base' found.
```
I’m not seeing any further error message that would indicate *why* Updates could not be refreshed, though. But let’s reopen this, looks like #137/#173 only covered the first part.

**Comment by dermarens** [comment] 2018-12-14 16:04
Stumbled upon this when trying to build openSUSE leap 42.3

Seems to work with another pattern, this is from inside the freshly built image

```
opensuse:~ # cat /etc/os-release 
NAME="openSUSE Leap"
VERSION="42.3"
ID=opensuse
ID_LIKE="suse"
VERSION_ID="42.3"
PRETTY_NAME="openSUSE Leap 42.3"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:opensuse:leap:42.3"
BUG_REPORT_URL="https://bugs.opensuse.org"
HOME_URL="https://www.opensuse.org/"
opensuse:~ # zypper se patterns-base-minimal_base
Loading repository data...
Reading installed packages...
No matching items found.
opensuse:~ # zypper se patterns-openSUSE-minimal_base
Loading repository data...
Reading installed packages...

S  | Name                                     | Summary     | Type   
---+------------------------------------------+-------------+--------
i+ | patterns-openSUSE-minimal_base           | Base System | package
   | patterns-openSUSE-minimal_base-conflicts | Base System | package
opensuse:~ # 
```

have a look at:

- https://software.opensuse.org/package/patterns-openSUSE-minimal_base
- https://software.opensuse.org/package/patterns-base-minimal_base

base-minimal_base seems to be supported only in the latest releases tumbleweed and leap-15

**Closed** 2019-06-27 01:11 UTC
Labels: bug, opensuse
