### ISSUE TITLE
Support physical devices

### ISSUE THREAD

**Issue by dteleguin** [systemd/mkosi#128] opened 2017-07-20 20:20 UTC
At the moment, mkosi can't operate physical devices directly. Running mkosi -o /dev/sdX will give an error in the final stage (Linking image...) because of the way image creation is implemented in mkosi.

Being able to write to physical devices, mkosi can have many useful applications, from creating live USBs to bare-metal server provisioning. At the same time, it shouldn't be hard to implement, as with physical devices we don't need all that loopback stuff.

Surely it is possible to `dd` an image to the disk, but there's no good solution for large disks. You'll either end up with a huge (probably TB-sized) image, or you can build smaller image and resize GPT+partitions+filesystems afterwards (and any additional manual steps like these could be undesirable from the point of view of automation).

**Comment by johannbg** [comment] 2019-01-21 15:32
Is this not a feature request for how alot of downstream distribution are doing this with "live" usb/cd ? 

Basically you create a image via mkosi, dd it to usb, boot the usb then run something live-cd-to-install. 

Could perhaps be a switch that simply adds type ( path? ) units and install to hardrive script run once at bootup to mkosi.extra which then would get build and placed on the image itself?

**Comment by lucasdemarchi** [comment] 2019-01-23 20:50
@johannbg well... I don't think this is the same thing. Writing directly on the usb device is good for not having to create a separate .raw image just to dd it later to a usb device...

I currently workaround that by estimating a minimal size for my images (usually 2 ~ 5 GB depending on the distro), dd it to the usb device and then resize the last partition (https://github.com/lucasdemarchi/toolbox/blob/master/mkosi-resize). See also https://github.com/systemd/mkosi/issues/239 - and see @poettering's answer regarding `x-systemd.growfs` which is already available in systemd since version 236.... that could be adopted here.

But supporting a physical device would be nice, too.

**Comment by valtzu** [comment] 2023-03-02 19:58
I think this is now resolved as mkosi uses systemd-repart. I was able to flash an SD card using mkosi from main branch with no issues.

**Comment by DaanDeMeyer** [comment] 2023-03-02 21:35
Can you elaborate? This issue is about having mkosi write directly to a block device, which we don't really support yet. I guess it might work if you point the output file to the block device but I would expect some rough edges.

**Comment by valtzu** [comment] 2023-03-02 21:40
> I guess it might work if you point the output file to the block device

Yeah, that's what I did, `mkosi build /dev/mmcblk0`, which worked for my use case.

> I would expect some rough edges.

I see, nevermind then.

**Comment by DaanDeMeyer** [comment] 2023-07-31 09:35
I'm going to close this one, as supporting physical devices in mkosi is not trivial. Instead, you can ship a set of systemd-repart definition files with your image and then you can run `systemd-repart --image <image> /dev/xxx` to deploy the image on the physical device after running mkosi. The image can be made minimal and systemd-repart will take care of growing the partitions when deploying to the actual device. With the growfs partition flag enabled systemd will automatically grow the filesystem to match the partition size on boot as well then.

**Closed by DaanDeMeyer** 2023-07-31 09:35 UTC
Labels: RFE

**Comment by leifliddy** [comment] 2025-03-23 21:32
Full disclosure for those of you whom have interacted with me before. I suffered a TBI last year whilst riding home from work.
I'm not quite back to my "old self" yet -- but I'm getting there. 
https://www.zvw.de/stuttgart-region/unfall-in-leinfelden-echterdingen-motorradfahrer-%C3%BCber-leitplanke-abgeworfen_arid-828214

I dont' quite understand how `systemd-repart `is meant to be used. It would be nice if someone could post step-by-step instructions on what exactly needs to be done before `systemd-repart --image <image> /dev/xxx` is run

I did the following. I placed the files listed here: https://www.leifliddy.com/etc/repart.d/ in `/etc/repart.d`
However, when I run `systemd-repart --image=` nothing happens. I'm  not sure what the issue is (obviously).
Any help would would be greatly appreciated. 


```
[root@m1 mkosi.output]# ll
total 1892584
lrwxrwxrwx. 1 root root          9 Mar 23 20:01 image -> image.raw
-rw-r--r--. 1 root root 3789574144 Mar 23 20:24 image.raw
-rwxr-xr-x. 1 root root   18895360 Mar 23 20:01 image.vmlinuz
[root@m1 mkosi.output]# 
[root@m1 mkosi.output]# 
[root@m1 mkosi.output]# 
[root@m1 mkosi.output]#  systemd-repart --image=image.raw /dev/sda
TYPE       LABEL      UUID                                 PARTNO FILE      RAW SIZE     SIZE PADDING
esp        esp        05fabdec-0d1f-4536-8d72-b4892751fa80 0               629145600     600M 0B
root-arm64 root-arm64 437a3770-900c-4fac-80ae-ed4df2296fef 1            536870912000     500G 0B
swap       swap       c5e959b5-1bce-42cc-bea1-b9d80a9341dc 2              1073741824       1G 0B
home       home       44d1f919-de4e-487e-a1b5-8c5eb4eb3885 3           1461825093632     1.3T 0B
                                                                                     Σ = 1.8T Σ = 0B

 ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
 │                              ├─ home                                                                              
 │                              └─ swap                                                                              
 ├─ root-arm64                                                                                                       
 └─ esp                                                                                                              

No changes.

```

**Comment by MoltenArmor** [comment] 2025-03-24 01:56
> Full disclosure for those of you whom have interacted with me before. I suffered a TBI last year whilst driving home from work. I'm not quite back to my "old self" yet -- but I'm getting there... https://www.zvw.de/stuttgart-region/unfall-in-leinfelden-echterdingen-motorradfahrer-%C3%BCber-leitplanke-abgeworfen_arid-828214
> 
> I dont' quite understand how `systemd-repart `is meant to be used. It would be nice if someone could post step-by-step instructions on what exactly needs to be done before `systemd-repart --image <image> /dev/xxx` is run
> 
> I did the following. I placed the files listed here: https://www.leifliddy.com/etc/repart.d/ in `/etc/repart.d` However, when I run `systemd-repart --image=` nothing happens. I'm not sure what the issue is (obviously). Any help would would be greatly appreciated.
> 
> ```
> [root@m1 mkosi.output]# cat /etc/redhat-release 
> Fedora release 42 (Adams)
> [root@m1 mkosi.output]# mkosi --version
> mkosi 25.3
> [root@m1 mkosi.output]# ls -lh *
> lrwxrwxrwx. 1 root root    9 Mar 23 20:01 image -> image.raw
> -rw-r--r--. 1 root root 3.6G Mar 23 20:24 image.raw
> -rwxr-xr-x. 1 root root  19M Mar 23 20:01 image.vmlinuz
> [root@m1 mkosi.output]# 
> [root@m1 mkosi.output]# 
> [root@m1 mkosi.output]# 
> [root@m1 mkosi.output]#  systemd-repart --image=image.raw /dev/sda
> TYPE       LABEL      UUID                                 PARTNO FILE      RAW SIZE     SIZE PADDING
> esp        esp        05fabdec-0d1f-4536-8d72-b4892751fa80 0               629145600     600M 0B
> root-arm64 root-arm64 437a3770-900c-4fac-80ae-ed4df2296fef 1            536870912000     500G 0B
> swap       swap       c5e959b5-1bce-42cc-bea1-b9d80a9341dc 2              1073741824       1G 0B
> home       home       44d1f919-de4e-487e-a1b5-8c5eb4eb3885 3           1461825093632     1.3T 0B
>                                                                                      Σ = 1.8T Σ = 0B
> 
>  ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒░
>  │                              ├─ home                                                                              
>  │                              └─ swap                                                                              
>  ├─ root-arm64                                                                                                       
>  └─ esp                                                                                                              
> 
> No changes.
> ```

Consider using `mkosi burn /dev/sda`?

**Comment by leifliddy** [comment] 2025-03-24 13:05
Thanks, I'll try that when I get home tonight. I suspect that the mkosi burn method of writing the image to disk likely comes with some limitations. It probably creates/uses a single partition. hmmm...I wonder if it could boot from via UEFI. 
I have a few projects that use mkosi that I haven't really touched in a while (nothing substantive anyway). 
ie
https://github.com/leifliddy/asahi-fedora-usb
https://github.com/leifliddy/asahi-rocky-usb

I should have probably mentioned that I attempted to get this working on an m1 macbook air (aarch64). I'll try on an x86_64 system tonight. I was thinking that maybe  my /etc/repart.d conf files had an issue. it would be nice to get systemd-repart working as the `copyfiles` functionality looks pretty cool.  If anyone has this working -- could you please post your repart.d configs along with the details of how you did it....as well as the architecture of the system  (x86_64, aarch64...etc). Even though it's not working for me at the moment -- I could take some solace in the fact that it does work for others....

**Comment by DaanDeMeyer** [comment] 2025-03-24 13:19
> Thanks, I'll try that when I get home tonight. I suspect that the mkosi burn method of writing the image to disk likely comes with some limitations. It probably creates/uses a single partition. hmmm...I wonder if it could boot from via UEFI. I have a few projects that use mkosi that I haven't really touched in a while (nothing substantive anyway). ie https://github.com/leifliddy/asahi-fedora-usb https://github.com/leifliddy/asahi-rocky-usb
> 
> I should have probably mentioned that I attempted to get this working on an m1 macbook air (aarch64). I'll try on an x86_64 system tonight. I was thinking that maybe my /etc/repart.d conf files had an issue. it would be nice to get systemd-repart working as the `copyfiles` functionality looks pretty cool. If anyone has this working -- could you please post your repart.d configs along with the details of how you did it....as well as the architecture of the system (x86_64, aarch64...etc). Even though it's not working for me at the moment -- I could take some solace in the fact that it does work for others....

https://github.com/systemd/particleos has a working configuration that uses `mkosi burn` to burn image to USB and repart configs to copy from USB to final target location.
