### ISSUE TITLE
Wrong release detect

### ISSUE THREAD

**Issue by reverendhomer** [systemd/mkosi#99] opened 2017-06-28 14:45 UTC
I have Ubuntu 17.04. `mkosi` fails on my machine because it tries to run `debootstrap` with `"17.04"` as a release. If I run debootstrap manually, it's saying `E: No such script: /usr/share/debootstrap/scripts/17.04`. I'm pretty sure it should be `zesty`, not `"17.04"`

**Comment by fsateler** [comment] 2017-06-28 15:54
This is duplicate of #82

**Closed by fsateler** 2017-06-28 15:54 UTC
Labels: duplicate
