### ISSUE TITLE
.manifest not put into mkosi.output

### ISSUE THREAD

**Issue by killermoehre** [systemd/mkosi#2415] opened 2024-02-20 18:19 UTC
Hi,

as you can see in https://github.com/b1-systems/openstack-ironic-images/actions/runs/7977325738/job/21779963828#step:10:4973, the manifest itself is written, but it's never proper renamed and put into `mkosi.output`.

It stays in `mkosi.cache` as `ubuntu~jammy~x86-64.manifest`. A name I never assigned.

**Comment by DaanDeMeyer** [comment] 2024-02-21 13:18
@killermoehre The manifest in mkosi.cache is a different one. I cannot reproduce the issue. Please provide a short mkosi config that reproduces the issue for you.

**Comment by killermoehre** [comment] 2024-02-21 16:35
`mkosi.conf`

```ini
[Distribution]
Distribution=ubuntu
Release=jammy
Repositories=
    main,
    multiverse,
    restricted,
    universe

[Output]
@ImageId=ubuntu-22.04-amd64
@ImageVersion=2023.05.23
Format=directory
CompressOutput=false
ManifestFormat=json

[Host]
Incremental=true
ToolsTree=default
```

with existing directories `mkosi.cache` and `mkosi.output`, called with `sudo mkosi build`.

**Comment by DaanDeMeyer** [comment] 2024-02-22 07:23
@killermoehre 

Running with your provided config, I get the following in mkosi.output:

```
➜  tmp git:(fix-kernel-install) ls mkosi.output/
ubuntu-22.04-amd64_2023.05.23/  ubuntu-22.04-amd64_2023.05.23.manifest  ubuntu-tools/
```

Are you running the latest version?

**Comment by killermoehre** [comment] 2024-02-22 09:23
I run 20.2 both on my Arch Linux and with the mkosi GitHub-Action on Ubuntu.

**Comment by DaanDeMeyer** [comment] 2024-02-22 09:27
@killermoehre Please try to reproduce with the latest version

**Comment by killermoehre** [comment] 2024-02-22 10:49
@DaanDeMeyer It works with mkosi-git. So a regression?

**Comment by DaanDeMeyer** [comment] 2024-02-22 10:50
@killermoehre Not sure, but we don't do stable releases or backports, so closing the issue. We'll do a new release sometime soon so you can move to that. For the moment; please pin a git commit and run from that.

**Closed by DaanDeMeyer** 2024-02-22 10:50 UTC
Labels: bug
