### ISSUE TITLE
`%i` in `UnifiedKernelImageFormat` ignores `ImageId` when using `Include`

### ISSUE THREAD

**Issue by davide125** [systemd/mkosi#3299] opened 2024-12-22 14:57 UTC
### mkosi commit the issue has been seen with

main

### Used host distribution

Fedora Linux Rawhide

### Used target distribution

Fedora Linux Rawhide

### Linux kernel version used

6.13.0-0.rc3.20241220git8faabc041a00.33.fc42

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

When using `Include`, it looks like we end up generating a UKI using the `ImageId` of the included config, even when it's overridden in the toplevel one. So in the example below, we set `ImageId=CakeOS`, and mkosi generates appropriately-named files in `mkosi.output` with a `CakeOS` prefix as expected, but within the image itself we end up with
```
‣  /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/boot/EFI/Linux/ParticleOS_20241222155117.efi size is 60.8M, consumes 60.8M.
```

I couldn't get a minimal repro together, so the one below is built on top of [ParticleOS](https://github.com/systemd/particleos). See https://github.com/davide125/arcadeos/tree/751d13ceee29843890440335832a89c3dc54f9a5 for a real-world example exposing this problem.

### Used mkosi config

```ini
$ git clone https://github.com/systemd/particleos
$ cat > mkosi.conf <<EOF
[Include]
Include=particleos

[Output]
ImageId=CakeOS
OutputDirectory=mkosi.output
EOF
$ mkosi genkey
$ mkosi -f
```

### mkosi output

```sh
‣ Running clean script /tmp/repro/particleos/mkosi.clean…
‣ Validating certificates and keys
‣ Copying cached package manager metadata
‣ Building CakeOS image
‣  Copying cached trees
‣  Copying in extra file trees…
‣  Running postinstall script /tmp/repro/particleos/mkosi.postinst.chroot…
Profile "local" was selected.
 
- with-systemd-homed is selected, make sure that the system-homed service is enabled
  - systemctl enable --now systemd-homed.service

‣  Signing systemd-boot binaries…
Wrote signed PE binary to /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed
‣  Installing systemd-boot…
Created "/buildroot/efi/EFI".
Created "/buildroot/efi/EFI/systemd".
Created "/buildroot/efi/EFI/BOOT".
Created "/buildroot/efi/loader".
Created "/buildroot/efi/loader/keys".
Created "/buildroot/boot/loader/entries".
Created "/buildroot/boot/EFI".
Created "/buildroot/boot/EFI/Linux".
Copied "/buildroot/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed" to "/buildroot/efi/EFI/systemd/systemd-bootx64.efi".
Copied "/buildroot/usr/lib/systemd/boot/efi/systemd-bootx64.efi.signed" to "/buildroot/efi/EFI/BOOT/BOOTX64.EFI".
Random seed file /buildroot/efi/loader/random-seed successfully written (32 bytes).
Created "/buildroot/efi/loader/keys/auto".
Secure boot auto-enrollment file /buildroot/efi/loader/keys/auto/PK.auth successfully written.
Secure boot auto-enrollment file /buildroot/efi/loader/keys/auto/KEK.auth successfully written.
Secure boot auto-enrollment file /buildroot/efi/loader/keys/auto/db.auth successfully written.
‣  Generating system users
‣  Generating volatile files
ACLs are not supported, ignoring.
ACLs are not supported, ignoring.
ACLs are not supported, ignoring.
ACLs are not supported, ignoring.
Symlink source path '/buildroot/usr/share/factory/etc/bashrc' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/bash.bashrc' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/bash.bash_logout' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/ca-certificates' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/crypto-policies' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/pki' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/pacman.conf' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/authselect' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/tuned' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/gdm' does not exist, skipping line.
Symlink source path '/buildroot/usr/share/factory/etc/geoclue' does not exist, skipping line.
fchownat() of /buildroot/etc/polkit-1/rules.d failed: Invalid argument
‣  Applying presets…
Created symlink '/buildroot/etc/systemd/system/systemd-homed.service.wants/systemd-homed-firstboot.service' → '/usr/lib/systemd/system/systemd-homed-firstboot.service'.
Created symlink '/buildroot/etc/systemd/system/sysinit.target.wants/systemd-network-generator.service' → '/usr/lib/systemd/system/systemd-network-generator.service'.
Created symlink '/buildroot/etc/systemd/system/dbus-org.freedesktop.timesync1.service' → '/usr/lib/systemd/system/systemd-timesyncd.service'.
Created symlink '/buildroot/etc/systemd/system/sysinit.target.wants/systemd-timesyncd.service' → '/usr/lib/systemd/system/systemd-timesyncd.service'.
Created symlink '/buildroot/etc/systemd/system/basic.target.wants/rpmdb-migrate.service' → '/usr/lib/systemd/system/rpmdb-migrate.service'.
Created symlink '/buildroot/etc/systemd/system/basic.target.wants/rpmdb-rebuild.service' → '/usr/lib/systemd/system/rpmdb-rebuild.service'.
Created symlink '/buildroot/etc/systemd/system/basic.target.wants/preset-global.service' → '/usr/lib/systemd/system/preset-global.service'.
Created symlink '/buildroot/etc/systemd/user/sockets.target.wants/ssh-agent.socket' → '/usr/lib/systemd/user/ssh-agent.socket'.
‣  Generating hardware database
‣  Removing files…
‣  Running finalize script /tmp/repro/particleos/mkosi.finalize…
‣  Generating disk image
MountPoint= is not specified for any eligible partitions, not generating /etc/fstab
EncryptedVolume= is not specified for any eligible partitions, not generating /etc/crypttab
Pre-populating erofs filesystem of partition 12-usr.conf twice to calculate minimal partition size
Preparing to populate erofs filesystem.
Ready to populate erofs filesystem.
mkfs.erofs 1.8.2
<W> erofs: EXPERIMENTAL libzstd compressor in use. Note that `fitblk` isn't supported by upstream zstd for now.
<W> erofs: Therefore it will takes more time in order to get the optimal result.
Build completed.
------
Filesystem UUID: f47ff682-f09c-4192-ae70-1bef0e81bf52
Filesystem total blocks: 101135 (of 4096-byte blocks)
Filesystem total inodes: 29021
Filesystem total metadata blocks: 6387
Filesystem total deduplicated bytes (of source files): 0
/var/tmp/.#repartfcc92ad54f609455 successfully formatted as erofs (uuid f47ff682-f09c-4192-ae70-1bef0e81bf52, no label)
Minimal partition size of erofs filesystem of partition 12-usr.conf is 395M
Automatically determined minimal disk image size as 1.7G.
Sized '/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.raw' to 1.7G.
Applying changes to /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.raw.
Copying in '/var/tmp/.#repartfcc92ad54f609455' (395M) on block level into future partition 3.
Copying in of '/var/tmp/.#repartfcc92ad54f609455' on block level completed.    
Syncing future partition 3 contents to disk.
Block level copying and synchronization of partition 3 complete in 224.367ms.
Syncing future partition 2 contents to disk.
Adding new partition 1 to partition table.
Adding new partition 2 to partition table.
Adding new partition 3 to partition table.
Writing new partition table.
All done.
‣  Generating UKI profile 'live'
Wrote unsigned /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/uki-profiles/live.efi
‣ /usr/lib/firmware/{amd-ucode,intel-ucode} not found, not adding microcode
‣  Building default initrd
‣   Copying cached trees
‣   Copying in extra file trees…
‣   Generating system users
‣   Generating volatile files
ACLs are not supported, ignoring.
ACLs are not supported, ignoring.
‣   Applying presets…
Created symlink '/buildroot/etc/systemd/system/sysinit.target.wants/systemd-network-generator.service' → '/usr/lib/systemd/system/systemd-network-generator.service'.
‣   Applying first boot settings
/buildroot: /etc/locale.conf written.
‣   Generating hardware database
‣   Removing 1 packages…
No matches were found for the following plugin name patterns while enabling libdnf plugins: builddep, versionlock
No matches were found for the following plugin name patterns while disabling libdnf plugins: *
Package                  Arch    Version                  Repository        Size
Removing:
 shadow-utils            x86_64  2:4.17.0~rc1-1.fc42      fedora         4.1 MiB
Removing unused dependencies:
 libsemanage             x86_64  3.8-0.rc3.1.fc42         fedora       305.3 KiB

Transaction Summary:
 Removing:           2 packages

Running transaction
[1/3] Prepare transaction               100% |  64.0   B/s |   2.0   B |  00m00s
[2/3] Removing shadow-utils-2:4.17.0~rc 100% |  35.7 KiB/s | 439.0   B |  00m00s
[3/3] Removing libsemanage-0:3.8-0.rc3. 100% | 214.0   B/s |  12.0   B |  00m00s
Complete!
‣   Removing files…
‣   Creating cpio archive /home/dcavalca/.cache/mkosi/mkosi-workspace-s83jkfpy/staging/initrd.cpio…
‣   Compressing /home/dcavalca/.cache/mkosi/mkosi-workspace-s83jkfpy/staging/initrd.cpio with zstd
‣   /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/initrd.cpio.zst size is 38.6M, consumes 38.6M.
‣  Running modinfo to fetch kernel module dependencies
‣  Calculating required kernel modules and firmware
‣  Creating cpio archive /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/kernel-modules-6.13.0-0.rc3.20241220git8faabc041a00.33.fc42.x86_64.initrd…
‣  Generating unified kernel image for kernel version 6.13.0-0.rc3.20241220git8faabc041a00.33.fc42.x86_64
+ systemd-sbsign sign --private-key /work/tmp/repro/mkosi.key --certificate /work/tmp/repro/mkosi.crt /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/usr/lib/modules/6.13.0-0.rc3.20241220git8faabc041a00.33.fc42.x86_64/vmlinuz --output /tmp/linux-signed4rhgdtg1
Wrote signed PE binary to /tmp/linux-signed4rhgdtg1
+ systemd-keyutil public --private-key /work/tmp/repro/mkosi.key
+ systemd-measure sign --osrel=/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/usr/lib/os-release --cmdline=/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/cmdline --uname=/tmp/tmp.unamek34u389w --pcrpkey=/tmp/tmp.pcrpkeyvmwjny0k --initrd=/tmp/tmp.initrdc7b683td --linux=/tmp/linux-signed4rhgdtg1 --sbat=/tmp/tmp.sbatfaz5kj4z --profile=/tmp/tmp.profiley3lq_9yf --bank=sha256 --private-key=/work/tmp/repro/mkosi.key
Copying section '.profile' from '/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/uki-profiles/live.efi': 40 bytes
Copying section '.cmdline' from '/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/uki-profiles/live.efi': 268 bytes
+ systemd-measure sign --profile=/tmp/tmp.profile08zo58ww --cmdline=/tmp/tmp.cmdline4nvhxbd0 --osrel=/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/usr/lib/os-release --uname=/tmp/tmp.unamek34u389w --pcrpkey=/tmp/tmp.pcrpkeyvmwjny0k --initrd=/tmp/tmp.initrdc7b683td --linux=/tmp/linux-signed4rhgdtg1 --sbat=/tmp/tmp.sbatfaz5kj4z --bank=sha256 --private-key=/work/tmp/repro/mkosi.key
+ systemd-sbsign sign --private-key /work/tmp/repro/mkosi.key --certificate /work/tmp/repro/mkosi.crt /tmp/uki58rhgvlo --output /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/boot/EFI/Linux/ParticleOS_20241222155117.efi
Wrote signed PE binary to /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/boot/EFI/Linux/ParticleOS_20241222155117.efi
Wrote signed /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/boot/EFI/Linux/ParticleOS_20241222155117.efi
‣  /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/root/boot/EFI/Linux/ParticleOS_20241222155117.efi size is 60.8M, consumes 60.8M.
‣  Formatting ESP/XBOOTLDR partitions
Automatically determined minimal disk image size as 1.7G, current image size is 1.7G.
File '/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.raw' already is of requested size or larger, not growing. (1.7G >= 1.7G)
Applying changes to /work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.raw.
Successfully wiped file system signatures from future partition 0.
Successfully discarded data from future partition 0.
Formatting future partition 0.
Preparing to populate vfat filesystem.
Ready to populate vfat filesystem.
mkfs.fat 4.2 (2021-01-31)
/var/tmp/repart-hDo2Sp successfully formatted as vfat (label "ESP", uuid c06022e5)
Successfully formatted future partition 0.
Syncing future partition 0 contents to disk.
Adding new partition 0 to partition table.
Writing new partition table.
All done.
‣  Extracting partitions
Automatically determined minimal disk image size as 1.7G, current image size is 1.7G.
File '/work/home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.raw' already is of requested size or larger, not growing. (1.7G >= 1.7G)
No changes.
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.raw to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.raw as they are located on different devices, falling back to copying
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.esp.raw to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.esp.raw as they are located on different devices, falling back to copying
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.usr-x86-64-verity-sig.c66b76b220404371924b037939e1ae3d.raw to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.usr-x86-64-verity-sig.c66b76b220404371924b037939e1ae3d.raw as they are located on different devices, falling back to copying
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.usr-x86-64-verity.3d0eaf3b35d9de56b07ef9bbed3f37f7.raw to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.usr-x86-64-verity.3d0eaf3b35d9de56b07ef9bbed3f37f7.raw as they are located on different devices, falling back to copying
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.usr-x86-64.cb8d1213f82eede6ec4fb24814a134fc.raw to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.usr-x86-64.cb8d1213f82eede6ec4fb24814a134fc.raw as they are located on different devices, falling back to copying
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.efi to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.efi as they are located on different devices, falling back to copying
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.vmlinuz to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.vmlinuz as they are located on different devices, falling back to copying
‣ Could not rename /home/dcavalca/.cache/mkosi/mkosi-workspace-6lhr4jbe/staging/CakeOS_20241222155117.initrd to /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.initrd as they are located on different devices, falling back to copying
‣  /tmp/repro/particleos/mkosi.output/CakeOS_20241222155117.raw size is 1.8G, consumes 461.6M.
```

**Comment by DaanDeMeyer** [comment] 2024-12-22 19:20
@davide125 specifiers are expanded inline while evaluating each setting, so doing Include=particleos before setting the image ID means the image id isn't set yet when including particleos. If you switch the order around it will work.

**Comment by DaanDeMeyer** [comment] 2024-12-23 08:57
Closing this since it's working as intended

**Closed by DaanDeMeyer** 2024-12-23 08:57 UTC
Labels: bug
