### ISSUE TITLE
`IndentationError: unexpected indent` during building of the image

### ISSUE THREAD

**Issue by NekkoDroid** [systemd/mkosi#2031] opened 2023-11-01 11:43 UTC
I have been testing mkosi a bit and it was working fine at the start (generated images successfully without problems). But after a while I was not able to generate images due to an error occurring:
```
Kernel version not specified, starting autodetection 😖.
Found uname version: 6.5.9-arch2-1
Wrote unsigned /home/nekko/Documents/mnt/mkosi.workspace/.mkosi-tmpe6456cyz/root/efi/EFI/Linux/arch_0.1
-6.5.9-arch2-1.efi
  File "<stdin>", line 1
    import pefile
IndentationError: unexpected indent
‣ "python3" returned non-zero exit code 1.
```

The config I've just been testing right now is
```
[Distribution]
Distribution=arch

[Content]
Packages=
    linux
    linux-firmware
    systemd
    systemd-sysvcompat

```

I am running on a relatively fresh install of ArchLinux with up-to-date (at the time of writing) packages.

I have tried reinstalling `mkosi` itself, as well as `python-pefile` but the error persists anyway

I will try on a completely blank system when I get the time (which should hopefully be soon) and will try to recreate the error there.

**Comment by NekkoDroid** [comment] 2023-11-01 12:41
So I just tested this again running on the live arch ISO. I was able to successfully build it there after downloading the required packages, so it seems to specifically be a problem on the installed system.

**Comment by behrmann** [comment] 2023-11-01 13:26
I gave the above config a try as well and it worked without (this particular) issue. Since it seems to work now, I'll close this, feel free to reopen if you can reproduce it.

**Comment by NekkoDroid** [comment] 2023-11-01 13:31
I am fine with it being closed now, the only thing I am still questioning is why the error appeared in the first place, since it seems it wasn't dedenting the output.

**Comment by NekkoDroid** [comment] 2023-11-02 20:55
Ok, after a bit of testing after the error popped up again I think I figured out what the cause is.

It seems like the image version (read from `mkosi.version`) gets a new line added to it, resulting in all the binary paths using that to have a new-line added to it. This results in the generated text in the previously linked section to have a new-line in it (with the remaining path in that new line), preventing the dedent (even manually dedenting the text, the new line breaks the string into 2 different lines causing a new error).

`print(pefile)` before the `run`
```
Signing Unsigned original image
Wrote signed /home/nekko/Documents/NekkOS/mkosi.workspace/.mkosi-tmp3ie4umlm/root/efi/EFI/Linux/NekkOS_0.1
-6.5.9-arch2-1.efi
        import pefile
        from pathlib import Path
        pe = pefile.PE("/home/nekko/Documents/NekkOS/mkosi.workspace/.mkosi-tmp3ie4umlm/root/efi/EFI/Linux/NekkOS_0.1
-6.5.9-arch2-1.efi", fast_load=True)
        section = {s.Name.decode().strip("\0"): s for s in pe.sections}[".initrd"]
        Path("/home/nekko/Documents/NekkOS/mkosi.workspace/.mkosi-tmp3ie4umlm/staging/NekkOS_0.1
.initrd").write_bytes(section.get_data(length=section.Misc_VirtualSize))

  File "<stdin>", line 1
    import pefile
IndentationError: unexpected indent
‣ "python3" returned non-zero exit code 1.
```

`OUTPUT` from `mkosi summary`
```
    OUTPUT:
                 Output Format: disk
              Manifest Formats: changelog
                        Output: NekkOS_0.1
.raw
                   Compression: none
              Output Directory: /home/nekko/Documents/NekkOS/mkosi.output
           Workspace Directory: /home/nekko/Documents/NekkOS/mkosi.workspace
               Cache Directory: /home/nekko/Documents/NekkOS/mkosi.cache/arch~rolling~x86-64
               Build Directory: /home/nekko/Documents/NekkOS/mkosi.builddir/arch~rolling~x86-64
                      Image ID: NekkOS
                 Image Version: 0.1

               Split Artifacts: no
            Repart Directories: /home/nekko/Documents/NekkOS/mkosi.repart
                   Sector Size: default
                       Overlay: no
                Use Subvolumes: auto
                          Seed: random
```

**Comment by NekkoDroid** [comment] 2023-11-02 21:28
I assume it is comes from [here](https://github.com/systemd/mkosi/blob/6bb142e511b2e73056bffe096c2951783f96a9eb/mkosi/config.py#L1238C8) since the [other location](https://github.com/systemd/mkosi/blob/6bb142e511b2e73056bffe096c2951783f96a9eb/mkosi/__init__.py#L2410) where the file is read does strip the file content

**Closed** 2023-11-03 19:48 UTC
