### ISSUE TITLE
chroot: cannot change root directory to '/work/postinst': No such file or directory

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1693] opened 2023-07-21 11:38 UTC
Done some digging but cannot make sense of this; the `bwrap ... || exit $? chroot /work/postinst final`  command looks wrong:
```
‣   Copying in extra file trees…
‣ + cp --recursive --no-dereference --preserve=mode,timestamps,links,xattr --no-target-directory --reflink=auto /home/tj/iam/mkosi/debian-
amd64-base/mkosi.extra /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root
‣   Running postinstall script…
‣ + bwrap --dev-bind / / --chdir /home/tj/iam/mkosi/debian-amd64-base --die-with-parent --tmpfs /home/tj/iam/mkosi/debian-amd64-base/mkosi
.workspace/.mkosi.tmpqww8bue3/root/run --tmpfs /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/tmp --proc /ho
me/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/proc --dev /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/
.mkosi.tmpqww8bue3/root/dev --ro-bind /sys /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/sys --bind /home/t
j/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/etc/passwd /etc/passwd --bind /home/tj/iam/mkosi/debian-amd64-base/m
kosi.workspace/.mkosi.tmpqww8bue3/root/etc/group /etc/group --bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3
/root/etc/shadow /etc/shadow --bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/etc/gshadow /etc/gshadow 
--setenv PATH /tmp/mkosi-scriptstltjd9ci:/usr/my/sbin:/usr/my/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --bind /var
/tmp/mkosi-var-tmp078ak327 /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/var/tmp --ro-bind /home/tj/iam/mko
si/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/etc/machine-id /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tm
pqww8bue3/root/etc/machine-id sh -c chmod 1777 /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/tmp /home/tj/i
am/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpqww8bue3/root/var/tmp /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp
qww8bue3/root/dev/shm && exec $0 "$@" || exit $? chroot /work/postinst final
chroot: cannot change root directory to '/work/postinst': No such file or directory
‣ "chroot /work/postinst final" returned non-zero exit code 125.
Traceback (most recent call last):
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 19, in propagate_failed_return
    yield
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 48, in main
    run_verb(args, presets)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2228, in run_verb
    build_image(args, config)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 1781, in build_image
    run_postinst_script(state)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 338, in run_postinst_script
    bwrap(
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 334, in bwrap
    raise e
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/run.py", line 328, in bwrap
    result = run([*cmdline, *cmd], env=env, log=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by DaanDeMeyer** [comment] 2023-07-21 12:46
Can you give me the output of `mount` on your system?

**Comment by iam-TJ** [comment] 2023-07-21 13:21
I tested it (and reported)  initially without my usual bind mounts to `mkosi.workspace` and `mkosi.output` so those were regular (empty) directories on my user profile. Happens with those bind mounts too. I `mv`ed `mkosi.postinst` out the way for now.

Mounts on my workstation are complicated since I use a LOT of LVs .... you are warned! Generated after setting up those bind mounts; sorted to make it easier to parse:
[mounts.txt](https://github.com/systemd/mkosi/files/12124987/mounts.txt)

**Comment by DaanDeMeyer** [comment] 2023-07-21 13:23
Yeah this is because your /tmp is mounted noexec. Should be fixed by https://github.com/systemd/mkosi/pull/1692

**Comment by iam-TJ** [comment] 2023-07-21 14:25
Hmm, it doesn't seem to be.
```
tj@sunny:/srv/NAS/Sunny/SourceCode/mkosi$ git l -n 16
96055dd 2023-07-21 15:20:47 +0100 N Tj Merge remote-tracking branch 'DaanDeMeyer/stuff'
6d730b9 2023-07-21 16:02:11 +0200 N Daan De Meyer Move more enums to config.py
be27fa3 2023-07-21 15:14:18 +0200 N Daan De Meyer Set TMPDIR=state.workspace when building an image
610582d 2023-07-21 14:55:41 +0200 N Daan De Meyer Drop filesystem_options() and make xfs default for centos again
7db09d7 2023-07-21 14:55:41 +0200 N Daan De Meyer Get rid of kernel_image() in DistributionInstaller
7ead0ca 2023-07-21 14:55:41 +0200 N Daan De Meyer Get rid of kernel_command_line() in DistributionInstaller
c9b5bcb 2023-07-21 14:55:41 +0200 N Daan De Meyer Fix do-a-release script
e502a67 2023-07-21 14:55:39 +0200 N Daan De Meyer Move Verb to config.py
8a29486 2023-07-21 11:55:11 +0200 E Daan De Meyer Merge pull request #1691 from DaanDeMeyer/distribution
6ed62ee 2023-07-21 11:41:57 +0200 N Daan De Meyer centos: Remove distribution specific checks
8d5c3cf 2023-07-21 11:41:19 +0200 N Daan De Meyer Simplify become_root()
3d196cd 2023-07-21 09:33:30 +0200 N Daan De Meyer fedora: Remove distribution specific checks
9271f2e 2023-07-20 16:27:07 +0200 N Daan De Meyer Kernel modules fixlets
ff6ae7f 2023-07-20 13:34:30 +0200 E Daan De Meyer Merge pull request #1686 from DaanDeMeyer/env
64558e6 2023-07-20 13:31:55 +0200 N Daan De Meyer Rework selinux labelling
cf4ff37 2023-07-20 11:49:37 +0200 N Daan De Meyer Only execute preset, hwdb, sysusers tools if they are available
```
I've attached the entire build log which is captured by my build script from:
```
$ sudo debug=true ./build.sh --distribution=debian --release=bookworm --image-id debian-bookworm-amd64 --auto-bump --force build
```
[mkosi.13.log](https://github.com/systemd/mkosi/files/12129620/mkosi.13.log)

**Comment by DaanDeMeyer** [comment] 2023-07-21 14:36
Woops, please pull and try again

**Comment by iam-TJ** [comment] 2023-07-21 14:45
OK, we have *partial* success in that:
```
‣   Running postinstall script…
‣ + bwrap --dev-bind / / --chdir /home/tj/iam/mkosi/debian-amd64-base --die-with-parent --tmpfs /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/run --tmpfs /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/tmp --proc /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/proc --dev /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/dev --ro-bind /sys /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/sys --bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/etc/passwd /etc/passwd --bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/etc/group /etc/group --bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/etc/shadow /etc/shadow --bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/etc/gshadow /etc/gshadow --setenv PATH /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/mkosi-scriptsnyw5_rca:/usr/my/sbin:/usr/my/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin --bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/mkosi-var-tmptuuvqg3v /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/var/tmp --ro-bind /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/etc/machine-id /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/etc/machine-id sh -c chmod 1777 /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/tmp /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/var/tmp /home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root/dev/shm && exec $0 "$@" || exit $? chroot /work/postinst final
SELinux enabled state cached to: disabled
Created symlink /etc/systemd/system/dbus-org.freedesktop.network1.service → /lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/multi-user.target.wants/systemd-networkd.service → /lib/systemd/system/systemd-networkd.service.
Created symlink /etc/systemd/system/sockets.target.wants/systemd-networkd.socket → /lib/systemd/system/systemd-networkd.socket.
Created symlink /etc/systemd/system/sysinit.target.wants/systemd-network-generator.service → /lib/systemd/system/systemd-network-generator.service.
Created symlink /etc/systemd/system/network-online.target.wants/systemd-networkd-wait-online.service → /lib/systemd/system/systemd-networkd-wait-online.service.
‣   Generating system users
...
```
but it then hits what may be a related issue:
```
...
final: BUILDROOT=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/root OUTPUTDIR=/home/tj/iam/mkosi/debian-amd64-ba
se/mkosi.workspace/.mkosi.tmp_0cf_7ma/staging
‣  Unmounting image…
‣  Copying nspawn settings file…
‣  Saving manifest debian-bookworm-amd64_0.2.manifest
‣  /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64 size is 414.7M.
/usr/lib/python3.11/tempfile.py:1034: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/home/tj/iam/mkosi/debian-amd64-base/mk
osi.workspace/.mkosi.tmp_0cf_7ma'>
  _warnings.warn(warn_message, ResourceWarning)
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 52, in <module>
    main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 48, in main
    run_verb(args, presets)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2246, in run_verb
    with mount_tools(last, umount=False), mount_passwd(name, uid, gid, umount=False):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/mounts.py", line 142, in mount_passwd
    with tempfile.NamedTemporaryFile(mode="w") as passwd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 702, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 699, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp_0cf_7ma/tmp4xz9sw
r4'
...
```
[mkosi.14.log](https://github.com/systemd/mkosi/files/12129816/mkosi.14.log)

**Comment by DaanDeMeyer** [comment] 2023-07-21 15:00
Can you try once more?

**Comment by iam-TJ** [comment] 2023-07-21 15:08
Still seeing a similar error:
```
final: BUILDROOT=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp4ip2mld1/root OUTPUTDIR=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp4ip2mld1/staging
‣  Unmounting image…
‣  Copying nspawn settings file…
‣  Saving manifest debian-bookworm-amd64_0.2.manifest
‣  /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64 size is 414.7M.
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 52, in <module>
    main()
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 48, in main
    run_verb(args, presets)
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2245, in run_verb
    with mount_tools(last, umount=False), mount_passwd(name, uid, gid, umount=False):
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/mounts.py", line 142, in mount_passwd
    with tempfile.NamedTemporaryFile(mode="w") as passwd:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 702, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 699, in opener
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/tempfile.py", line 395, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp4ip2mld1/tmp2_27i2
g9'
# clear builtins._
[mkosi.15.log](https://github.com/systemd/mkosi/files/12130029/mkosi.15.log)

```

That is with:
```
$ git reset --hard origin/main
HEAD is now at 8a29486 Merge pull request #1691 from DaanDeMeyer/distribution
tj@sunny:/srv/NAS/Sunny/SourceCode/mkosi$ git fetch DaanDeMeyer
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), 774 bytes | 387.00 KiB/s, done.
From https://github.com/DaanDeMeyer/mkosi
   5935095..fd95c1d  stuff      -> DaanDeMeyer/stuff
tj@sunny:/srv/NAS/Sunny/SourceCode/mkosi$ git merge --no-ff DaanDeMeyer/stuff
Merge made by the 'ort' strategy.
 mkosi/__init__.py               | 43 ++++++++++++++-----------------------------
 mkosi/config.py                 | 72 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++------------
 mkosi/distributions/__init__.py | 13 -------------
 mkosi/distributions/centos.py   | 45 +--------------------------------------------
 mkosi/distributions/debian.py   | 15 +++++++++------
 mkosi/distributions/gentoo.py   | 21 +++++++++++----------
 mkosi/manifest.py               |  4 ++--
 mkosi/qemu.py                   |  6 ++----
 mkosi/run.py                    |  4 ++--
 mkosi/state.py                  | 16 +++++++++++++---
 mkosi/util.py                   | 95 ++++++++++++++++++++++++++---------------------------------------------------------------------
 tests/test_parse_load_args.py   |  4 ++--
 tools/do-a-release.sh           |  2 +-
 13 files changed, 143 insertions(+), 197 deletions(-)
tj@sunny:/srv/NAS/Sunny/SourceCode/mkosi$ git l -n 16
5c9deb9 2023-07-21 16:03:14 +0100 N Tj Merge remote-tracking branch 'DaanDeMeyer/stuff'
fd95c1d 2023-07-21 16:59:00 +0200 N Daan De Meyer Make MkosiState a context manager
5935095 2023-07-21 16:36:22 +0200 N Daan De Meyer Move more enums to config.py
e8b35aa 2023-07-21 16:36:20 +0200 N Daan De Meyer Set TMPDIR=state.workspace when building an image
610582d 2023-07-21 14:55:41 +0200 N Daan De Meyer Drop filesystem_options() and make xfs default for centos again
7db09d7 2023-07-21 14:55:41 +0200 N Daan De Meyer Get rid of kernel_image() in DistributionInstaller
7ead0ca 2023-07-21 14:55:41 +0200 N Daan De Meyer Get rid of kernel_command_line() in DistributionInstaller
c9b5bcb 2023-07-21 14:55:41 +0200 N Daan De Meyer Fix do-a-release script
e502a67 2023-07-21 14:55:39 +0200 N Daan De Meyer Move Verb to config.py
8a29486 2023-07-21 11:55:11 +0200 E Daan De Meyer Merge pull request #1691 from DaanDeMeyer/distribution
6ed62ee 2023-07-21 11:41:57 +0200 N Daan De Meyer centos: Remove distribution specific checks
8d5c3cf 2023-07-21 11:41:19 +0200 N Daan De Meyer Simplify become_root()
3d196cd 2023-07-21 09:33:30 +0200 N Daan De Meyer fedora: Remove distribution specific checks
9271f2e 2023-07-20 16:27:07 +0200 N Daan De Meyer Kernel modules fixlets
ff6ae7f 2023-07-20 13:34:30 +0200 E Daan De Meyer Merge pull request #1686 from DaanDeMeyer/env
64558e6 2023-07-20 13:31:55 +0200 N Daan De Meyer Rework selinux labelling
```

**Comment by DaanDeMeyer** [comment] 2023-07-21 15:30
And the output of `stat mkosi.workspace`

**Comment by iam-TJ** [comment] 2023-07-21 15:42
```
$ stat mkosi.workspace
  File: mkosi.workspace
  Size: 514             Blocks: 32         IO Block: 4096   directory
Device: 0,57    Inode: 256         Links: 1
Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (  996/machines)
Access: 2023-07-21 16:06:07.777727936 +0100
Modify: 2023-07-21 16:32:48.492607634 +0100
Change: 2023-07-21 16:32:48.492607634 +0100
 Birth: 2021-09-30 08:34:34.000000000 +0100
```

```
‣  Unmounting image…                                                 
‣  Copying nspawn settings file…                                     
‣  Saving manifest debian-bookworm-amd64_0.2.manifest                
‣  /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64 size is 414.7M.                                                
Traceback (most recent call last):                                   
  File "<frozen runpy>", line 198, in _run_module_as_main                                                                                 
  File "<frozen runpy>", line 88, in _run_code                       
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 52, in <module>                                                          
    main()                                                           
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner        
    return func(*args, **kwds)                                       
           ^^^^^^^^^^^^^^^^^^^                                                                                                            
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 48, in main                                                              
    run_verb(args, presets)                                          
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__init__.py", line 2245, in run_verb                                                        
    with mount_tools(last, umount=False), mount_passwd(name, uid, gid, umount=False):                                                     
  File "/usr/lib/python3.11/contextlib.py", line 137, in __enter__   
    return next(self.gen)                                            
           ^^^^^^^^^^^^^^                                            
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/mounts.py", line 143, in mount_passwd                                                       
    with tempfile.NamedTemporaryFile(mode="w") as passwd:            
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                            
  File "/usr/lib/python3.11/tempfile.py", line 702, in NamedTemporaryFile
    file = _io.open(dir, mode, buffering=buffering,                  
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                  
  File "/usr/lib/python3.11/tempfile.py", line 699, in opener        
    fd, name = _mkstemp_inner(dir, prefix, suffix, flags, output_type)                                                                    
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                    
  File "/usr/lib/python3.11/tempfile.py", line 395, in _mkstemp_inner                                  
    fd = _os.open(file, flags, 0o600)                                
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                
FileNotFoundError: [Errno 2] No such file or directory: '/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp6wo1nzgm/tmph7x8cl
96'                                                                  
mount_passwd() TMPDIR=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmp6wo1nzgm
```

**Comment by iam-TJ** [comment] 2023-07-21 15:46
In case it is relevant, previously due to issues with bubblewrap you recommended this, which my `build.sh` is doing:
```
# needed due to containers being built in unprivileged namespace so creation needs doing as UID 0, not as the invoking UID
unset -v SUDO_UID
```

**Comment by DaanDeMeyer** [comment] 2023-07-21 18:52
@iam-TJ Are you sure you have the latest version of my branch? I cannot reproduce the issue.

**Comment by iam-TJ** [comment] 2023-07-21 19:09
I'm pretty sure it was the latest when I tested; I do:
```
git fetch DaanDeMeyer
git reset --hard origin/main
git merge --no-ff DaanDeMeyer/stuff
```
This is the log after repeating that process right now:
```
tj@sunny:/srv/NAS/Sunny/SourceCode/mkosi$ git l -n 10
56aad1e 2023-07-21 20:02:58 +0100 N Tj Merge remote-tracking branch 'DaanDeMeyer/stuff'
51da1ad 2023-07-21 20:48:11 +0200 N Daan De Meyer mount_passwd() cleanups
adf0f79 2023-07-21 20:38:46 +0200 N Daan De Meyer Make MkosiState a context manager
ef0df26 2023-07-21 20:38:44 +0200 N Daan De Meyer Move more enums to config.py
e8b35aa 2023-07-21 16:36:20 +0200 N Daan De Meyer Set TMPDIR=state.workspace when building an image
610582d 2023-07-21 14:55:41 +0200 N Daan De Meyer Drop filesystem_options() and make xfs default for centos again
7db09d7 2023-07-21 14:55:41 +0200 N Daan De Meyer Get rid of kernel_image() in DistributionInstaller
7ead0ca 2023-07-21 14:55:41 +0200 N Daan De Meyer Get rid of kernel_command_line() in DistributionInstaller
c9b5bcb 2023-07-21 14:55:41 +0200 N Daan De Meyer Fix do-a-release script
e502a67 2023-07-21 14:55:39 +0200 N Daan De Meyer Move Verb to config.py
tj@sunny:/srv/NAS/Sunny/SourceCode/mkosi$ date
Fri 21 Jul 20:03:42 BST 2023
```
Running another build - should I have re-added the `TMPDIR=` report because I didn't commit it!? OK, build was successful!
```
final: BUILDROOT=/home/tj/iam/mkosi/debian-amd64-base/mkosi.workspace/.mkosi.tmpg7km3p8z/root OUTPUTDIR=/home/tj/iam/mkosi/debian-amd64-ba
se/mkosi.workspace/.mkosi.tmpg7km3p8z/staging
‣  Unmounting image…
‣  Copying nspawn settings file…
‣  Saving manifest debian-bookworm-amd64_0.2.manifest
‣  /home/tj/iam/mkosi/debian-amd64-base/mkosi.output/debian-bookworm-amd64 size is 414.7M.
‣ Increasing last component of version by one, bumping '0.2' → '0.3'.
# clear builtins._
```
Now just need to get the BTRFS subvolume output back! ( Issue  #1694 )

**Closed** 2023-07-22 20:31 UTC
