### ISSUE TITLE
mkosi re-creates the $PWD directory structure inside Fedora/CentOS/RHEL/etc. images

### ISSUE THREAD

**Issue by NoisyCoil** [systemd/mkosi#2047] opened 2023-11-06 20:52 UTC
As per title. If mkosi is run from, say, /home/username/tmp/mkosi, then the same directory structure is created inside the image. To reproduce:

```sh
$ mkdir -p /home/username/tmp/mkosi && cd /home/username/tmp/mkosi

$ mkosi -d fedora -t directory --bootable no

...

$ ls image
afs  bin  boot  dev  efi  etc  home  lib  lib64  media  mnt  opt  proc  root  run  sbin  srv  sys  tmp  usr  var

$ tree image/home
image/home
└── username
    └── tmp
        └── mkosi
```

This happens when building Fedora, CentOS, RHEL, Alma Linux and Rocky Linux images. It does not happen when building Debian, Ubuntu and Gentoo images. I did not try with other OSes. I tried both v18 and the current main installed with pip.

**Comment by DaanDeMeyer** [comment] 2023-11-06 20:59
This seems to be a bug in dnf as I can reproduce with dnf but not with dnf5.

**Comment by DaanDeMeyer** [comment] 2023-12-14 13:03
Let's close this here as the bug has been confirmed in dnf and should be fixed there.

**Closed by DaanDeMeyer** 2023-12-14 13:03 UTC
Labels: not-our-bug
