### ISSUE TITLE
Debian-based images don't boot when using BIOS protocol

### ISSUE THREAD

**Issue by lukasstockner** [systemd/mkosi#828] opened 2021-10-06 14:49 UTC
When building bootable Debian-based images with BIOS selected as the boot protocol, the resulting image fails to boot.

For example, this can be reproduced with
```
mkosi --distribution debian --format gpt_ext4 --bootable --boot-protocol bios qemu
```

From what I can see, there seem to be two issues:
- Dracut never runs, so there is no initrd in `/boot`
- The Grub config defaults to using `/dev/loopXp2` as the root partition, which of course fails when booting the image in a VM or on bare metal

Both of these can be fixed in a postinst script (by running `dpkg-reconfigure` on the kernel package and setting `GRUB_DISABLE_LINUX_UUID` to false in `/etc/default/grub`), but they should probably be part of the `mkosi` logic by default.

**Comment by DaanDeMeyer** [comment] 2022-06-16 18:32
Can't reproduce this on the main branch, dracut runs and the image boots so should be fixed in the next release

**Closed by DaanDeMeyer** 2022-06-16 18:32 UTC
