### ISSUE TITLE
Error when trying to make Debian image without specifying the release

### ISSUE THREAD

**Issue by AsciiWolf** [systemd/mkosi#82] opened 2017-05-17 19:02 UTC
This strange error appears if I try to make Debian image using mkosi under Debian unstable without specifying the release manually:

![error](https://cloud.githubusercontent.com/assets/2339930/26170573/3622e2e0-3b42-11e7-8457-90aec5839193.png)

It looks like the default _args.release_ variable is not correctly parsed. This bug is not present under Ubuntu 16.04 on my another machine.

Here is the full traceback:

```
Traceback (most recent call last):
  File "/usr/local/bin/mkosi", line 2538, in <module>
    main()
  File "/usr/local/bin/mkosi", line 2534, in main
    build_stuff(args)
  File "/usr/local/bin/mkosi", line 2486, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, run_build_script=False)
  File "/usr/local/bin/mkosi", line 2384, in build_image
    install_distribution(args, workspace.name, run_build_script)
  File "/usr/local/bin/mkosi", line 1015, in install_distribution
    install[args.distribution](args, workspace, run_build_script)
  File "/usr/lib/python3.5/contextlib.py", line 30, in inner
    return func(*args, **kwds)
  File "/usr/local/bin/mkosi", line 833, in install_debian
    install_debian_or_ubuntu(args, workspace, run_build_script, args.mirror)
  File "/usr/local/bin/mkosi", line 778, in install_debian_or_ubuntu
    subprocess.run(cmdline, check=True)
  File "/usr/lib/python3.5/subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--merged-usr', '--variant=minbase', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=main', '"9"', '/var/tmp/mkosi-488qxli3/root', 'http://httpredir.debian.org/debian']' returned non-zero exit status 1
```

**Comment by fsateler** [comment] 2017-05-18 14:32
Do you have a `mkosi.default` lying around? I have seen that happen where `/u/s/debootstrap/scripts/23` does not exist (23 being the fedora release in the `mkosi.default` file)

**Comment by AsciiWolf** [comment] 2017-05-19 10:28
@fsateler I don't.

**Comment by reverendhomer** [comment] 2017-06-28 14:38
I have the same issue. I've checked this subprocess by running it manually. `debootstrap` reports `E: unrecognized or invalid option --merged-usr`.

Ubuntu 17.04

**Comment by fsateler** [comment] 2017-06-28 15:53
@reverendhomer your issue is not the same, the problem is that ubuntu does not have --merged-usr. The problem is that mkosi by default reads os-release, and gets the VERSION_ID. In debian that field is the numeric version, but debootstrap does not understand the numeric versions. Not sure what to do about this...

**Comment by poettering** [comment] 2017-06-28 16:51
@fsateler does debian encode the name to us in /etc/os-release? What's the field's name?

**Comment by AsciiWolf** [comment] 2017-06-28 19:54
@fsateler It is a numeric version on Ubuntu as well. Ubuntu has /etc/lsb-release with DISTRIB_CODENAME, but Debian does not have that file.

**Comment by fsateler** [comment] 2017-06-28 22:56
@poettering not yet, this was not fixed by the base-files maintainer yet: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829245

**Comment by poettering** [comment] 2017-07-03 11:35
> In debian that field is the numeric version, but debootstrap does not understand the numeric versions. Not sure what to do about this...

maybe add a short dictionary for now that just translates the numbers to names? I mean, we have a dictionary for the fedora gpg keys, too...

**Comment by kBite** [comment] 2017-07-18 12:00
I get the same error running `mkosi` without `-r xenial` at Ubuntu 16.04:
```
$ mkosi
DISTRIBUTION:
          Distribution: ubuntu
               Release: "16.04"
                Mirror: http://archive.ubuntu.com/ubuntu
...
‣ Installing Ubuntu...
E: No such script: /usr/share/debootstrap/scripts/"16.04"
‣ Unmounting Package Cache...
...
subprocess.CalledProcessError: Command '['debootstrap', '--verbose', '--merged-usr', '--variant=minbase', '--include=systemd-sysv', '--exclude=sysv-rc,initscripts,startpar,lsb-base,insserv', '--components=main', '"16.04"', '/var/tmp/mkosi-ah9mcr96/root', 'http://archive.ubuntu.com/ubuntu']' returned non-zero exit status 1
```


Thus this issue's scope might be changed to *debian-based* or *Debian/Ubuntu* as those are the only supported debian-based distributions.

**Comment by q2dg** [comment] 2017-12-06 21:08
Well..I'm running mkosi on Ubuntu 17.10 (artful)
If I do mkosi                                  I get this error
If I do mkosi -d debian                  it works ok (it fetchs "unstable" branch)
If I do mkosi -d debian -r jessie     I get this error
If I do mkosi -d debian -r stretch   I get this error
If I do mkosi -d ubuntu                  I get this error
If I do mkosi -d ubuntu -r xenial    it works ok
If I do mkosi -d ubuntu -r artful     it works ok

I don't know if it has any logical reason

**Comment by poettering** [comment] 2018-02-12 15:22
I figure we can close this now that #224 has been merged.

**Closed by poettering** 2018-02-12 15:22 UTC
