### ISSUE TITLE
UEFI SecureBoot enabled, but couldn't find private key

### ISSUE THREAD

**Issue by iam-TJ** [systemd/mkosi#1733] opened 2023-08-05 07:40 UTC
I decided to build latest `systemd` using the mkosi method and had the foresight to use my usual 'debug' scripting to capture as much logging as possible.

Despite the host not having SecureBoot enabled it fails with:
```
UEFI SecureBoot enabled, but couldn't find private key.
```
However:
```
$ mokutil --sb-state
SecureBoot disabled
```
So I was initially perplexed, then on reading the code it seems as if the message relates to a configuration value:
```
    if args.secure_boot and args.verb != Verb.genkey:
        if args.secure_boot_key is None:
            die("UEFI SecureBoot enabled, but couldn't find private key.",
                hint="Consider placing it in mkosi.key")
```
And indeed I find, in systemd source:
```
mkosi.presets/20-final/mkosi.conf:43:SecureBoot=yes
```
Could this message (and related messages) be refined to indicate it is referring to the build configuration NOT the host status?

The build log:
```
...
# code object from /srv/NAS/Sunny/SourceCode/mkosi/mkosi/tree.py
import 'mkosi.tree' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb9bc2f3440>
import 'mkosi.qemu' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb9bc47ad60>
# code object from /srv/NAS/Sunny/SourceCode/mkosi/mkosi/state.py
# code object from /srv/NAS/Sunny/SourceCode/mkosi/mkosi/distributions/__init__.py
import 'mkosi.distributions' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb9bc300470>
import 'mkosi.state' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb9bc2d5140>
import 'mkosi' # <_frozen_importlib_external.SourceFileLoader object at 0x7fb9bd4437b0>
# code object from /srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py
‣ + timedatectl show -p Timezone --value
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 si
gnature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.2038 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1 signature=s error-name=n/
a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.timedate1 path=/org/freedesktop/timedate1 interface=org.freedesktop.DBus.Properties member=GetAll cook
ie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=:1.2039 destination=:1.2038 path=n/a interface=n/a member=n/a cookie=4 reply_cookie=2 signature=a{sv} error-name=n/a error-message=n/
a
Bus n/a: changing state RUNNING → CLOSED
‣ + timedatectl show -p Timezone --value
...
Bus n/a: changing state UNSET → OPENING
sd-bus: starting bus by connecting to /run/dbus/system_bus_socket...
Bus n/a: changing state OPENING → AUTHENTICATING
Bus n/a: changing state AUTHENTICATING → HELLO
Sent message type=method_call sender=n/a destination=org.freedesktop.DBus path=/org/freedesktop/DBus interface=org.freedesktop.DBus member=Hello cookie=1 reply_cookie=0 si
gnature=n/a error-name=n/a error-message=n/a
Got message type=method_return sender=org.freedesktop.DBus destination=:1.2041 path=n/a interface=n/a member=n/a cookie=4294967295 reply_cookie=1 signature=s error-name=n/
a error-message=n/a
Bus n/a: changing state HELLO → RUNNING
Sent message type=method_call sender=n/a destination=org.freedesktop.timedate1 path=/org/freedesktop/timedate1 interface=org.freedesktop.DBus.Properties member=GetAll cook
ie=2 reply_cookie=0 signature=s error-name=n/a error-message=n/a
Got message type=method_return sender=:1.2039 destination=:1.2041 path=n/a interface=n/a member=n/a cookie=8 reply_cookie=2 signature=a{sv} error-name=n/a error-message=n/
a
Bus n/a: changing state RUNNING → CLOSED
‣ UEFI SecureBoot enabled, but couldn't find private key.
‣ (Consider placing it in mkosi.key)
Traceback (most recent call last):
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 19, in propagate_failed_return
    yield
  File "/usr/lib/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/__main__.py", line 43, in main
    args, presets = MkosiConfigParser().parse()
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 1856, in parse
    return args, tuple(load_config(ns) for ns in presets)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 1856, in <genexpr>
    return args, tuple(load_config(ns) for ns in presets)
                       ^^^^^^^^^^^^^^^
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/config.py", line 2162, in load_config
    die("UEFI SecureBoot enabled, but couldn't find private key.",
  File "/srv/NAS/Sunny/SourceCode/mkosi/mkosi/log.py", line 30, in die
    sys.exit(1)
SystemExit: 1
```

**Comment by DaanDeMeyer** [comment] 2023-08-05 10:38
You need to run `mkosi genkey` first or configure your own private key. See the HACKING guide in the systemd repository

**Comment by DaanDeMeyer** [comment] 2023-08-05 10:40
This is not a bug so closing

**Closed by DaanDeMeyer** 2023-08-05 10:40 UTC
