### ISSUE TITLE
Ubuntu 20.04 build issues

### ISSUE THREAD

**Issue by brpatel12** [systemd/mkosi#891] opened 2022-01-21 21:51 UTC
Hi all - couple of questions. I'm trying to build a base Ubuntu image before attempting to migrate a larger build process to entirely generate images using mkosi. I assume I'm making a mistake somewhere and am hoping for some assistance.
- Ubuntu 20.04 LTS
- NVIDIA GPU

# Configs
build produces an image with kernel `5.4.0-26-generic`

## Version
```bash
brpatel@bergie:~/mkosi$ mkosi --version
mkosi 12
```

## mkosi.default
```bash
[Distribution]
Distribution=ubuntu
Release=focal
Repositories=focal,main,restricted,universe
Architecture=x86_64

[Output]
Format=gpt_ext4
ManifestFormat=json
OutputDirectory=mkosi.output
ImageId=test
ImageVersion=1
SplitArtifacts=no
Bootable=yes
BootProtocols=uefi
SecureBoot=no
ReadOnly=no
Minimize=no

[Content]
WithNetwork=yes
Cache=mkosi.cache
BasePackages=yes

Packages=
  sudo
  vim
  iputils-ping
  less
  lsof

  # syslog
  #rsyslog
  inetutils-syslogd

CleanPackageMetadata=auto
Password=test
ExtraTree=mkosi.extra
PostInstallationScript=mkosi_postinst.sh

[Partitions]
RootSize=5G
ESPSize=1G
```
## mkosi.extra
```bash
brpatel@bergie:~/mkosi$ tree mkosi.extra/
mkosi.extra/
└── etc
    └── apt
        └── sources.list
```
## /etc/apt/sources.list
```bash
deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe multiverse
deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe multiverse
deb http://security.ubuntu.com/ubuntu focal-security main restricted universe multiverse
```
## mkosi_postinst.sh
```bash
#!/bin/bash
set -euo pipefail

apt-get -y update
apt-get -y upgrade
apt-get install -y --no-install-recommends nvidia-driver-470 
apt-get -y update
```
# Issues
when I boot with qemu or the target hardware I run into the same issues - appreciate any suggestions

## systemd services
- A bunch of systemd services are failing during boot, most seem to be due to some type of permissions error. An example is `systemd-resolved.service` or `nvidia-persistenced.service` which have permissions errors
  - [photo with output](https://drive.google.com/file/d/1yLN4CFRzmjBUzox3ZonX2VlyGNvX2J4V/view?usp=sharing) - I confirmed the permissions and owners are the same as a "regularly" installed Ubuntu system

- I see `W: Download is performed unsandboxed as root as file '/var/cache/apt/archives/partial/tree_1.8.0-1_amd64.deb' couldn't be accesseded by user '_apt'. pkgAcquire::Run (13: Permission denied)` at various points in the mkosi build process which may or may not be related

**Comment by dellgreen** [comment] 2022-01-22 00:57
initially, try removing bind9 as it could be conflicting with systemd as i think it has its own dns resolver.

**Comment by brpatel12** [comment] 2022-01-22 00:59
> initially, try removing bind9 as it could be conflicting with systemd as i think it has its own dns resolver.

Whoops. Shouldn't have included that in my post since I added that after-the-fact while debugging (so I've already tried with and without bind9).

**Comment by behrmann** [comment] 2022-01-24 13:30
@brpatel12: The apt messages about doing the download unsandboxed are mostly harmless. It just means that apt could do the downloads as the less priviliged `_apt` user for some reason. In your case, it seems, that there already is a downloaded file owned by root, that `_apt` can't access.

To see why resolved doesn't work, could you show us the journal output?

**Comment by brpatel12** [comment] 2022-01-24 16:07
Journal output is attached in the picture I linked (wasn't able to figure out copy paste with qemu, but I'll try and figure it out again later today)

**Comment by behrmann** [comment] 2022-01-24 16:10
Sorry for being unclear: I'd like the output of `journalctl -u systemd-resolved.service`, since the few journal lines in the picture only show, that resolved was restarted multiple times and reached its restart limit.

**Comment by brpatel12** [comment] 2022-01-24 16:21
That was clear (my fault), here's the output:

![image](https://user-images.githubusercontent.com/32556395/150821967-03d6450d-9cb9-46aa-9e0b-67fe44e3787e.jpeg)

**Comment by behrmann** [comment] 2022-01-24 16:41
Looks like your problem is more systemic. The services can't connect to the journal and resolved fails during its startup with an error on chdir. 

Can you try to generate just a Ubuntu image to see whether that works at all? I'd like to see at which point this error creeps in.

**Comment by brpatel12** [comment] 2022-01-27 01:28
The problem originally arose when adding the `/etc/apt/sources.list` configuration file (either skeleton or extra). Removing mkosi.skeleton / mkosi.extra allowed me to successfully boot.

```bash
# mkosi.default
[Distribution]
Distribution=ubuntu
Release=focal
Repositories=main
Architecture=x86_64

[Output]
Format=gpt_ext4
OutputDirectory=mkosi.output
ImageId=test
ImageVersion=35
Bootable=yes
BootProtocols=uefi

[Content]
WithNetwork=yes
Packages=
  ubuntu-minimal
CleanPackageMetadata=auto
Password=test

SkeletonTree=mkosi.skeleton
#ExtraTree=mkosi.extra

[Partitions]
RootSize=2G
ESPSize=1G
```


I tried adding `sources.list` via both skeleton and extra which both resulted in the same systemd failures during boot:
```bash
brpatel@bergie:~/mkosi$ tree
├── mkosi.default
├── mkosi.extra
│   └── etc
│       └── apt
│           └── sources.list
└── mkosi.output
```
```bash
brpatel@bergie:~/mkosi$ tree
.
├── mkosi.default
├── mkosi.output
└── mkosi.skeleton
    └── etc
        └── apt
            └── sources.list
```

I was able to add these via a `mkosi.postinst` script and successfully boot:
```bash
apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe"
apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe"
apt-add-repository "deb http://security.ubuntu.com/ubuntu focal-security main restricted universe"
```

Same problems if I add `mkosi.skeleton/etc/resolv.conf`
```bash
nameserver 127.0.0.53
options edns0 trust-ad
```

Same problems if I add `mkosi.skeleton/etc/netplan/01-netcfg.yaml` (this doesn't overwrite any existing config file)
```bash
network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      dhcp4: true
      dhcp6: true
```

Seems like a problem with how skeleton/extra are being handled, but more likely I'm making a mistake somewhere. Thanks again for the help.

**Comment by brpatel12** [comment] 2022-01-31 22:54
@behrmann any other ideas? I tried using a tar instead of the directory structure `mkosi.skeleton.tar` and am running into the same systemd failures on boot.

**Comment by behrmann** [comment] 2022-02-02 09:16
Sorry, had this open a couple of days but forgot to actually reply. 

So let me summarise your findings: When installing an `/etc/apt/sources.list` via `mkosi.skeleton` or `mkosi.extra` the machine doesn't boot, when running 
```bash
#!/bin/bash
set -euo pipefail

# apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe"
# apt-add-repository "deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe"
# apt-add-repository "deb http://security.ubuntu.com/ubuntu focal-security main restricted universe"
apt-get -y update
apt-get -y upgrade
apt-get install -y --no-install-recommends nvidia-driver-470 
apt-get -y update
```
but it works if you *don't* change `/etc/apt/sources.list` via `mkosi.skeleton` or `mkosi.extra`, but comment in the above `apt-add-repository` lines? Would that be the minimal reproducer?

If so, what is the state of `/etc/apt/sources.list` before changing the repositories? If you just overwrite `/etc/apt/sourcest.list` you would lose what was in there before, while `apt-add-repository` will be additive. You could also just drop additional `.list` files into `/etc/apt/sources.list.d/`.

The relevant code is in `build_image`
```python
install_skeleton_trees(args, root, cached_tree)
install_distribution(args, root, do_run_build_script, cached_tree)
install_etc_hostname(args, root, cached_tree)
install_boot_loader(args, root, loopdev, do_run_build_script, cached_tree)
run_prepare_script(args, root, do_run_build_script, cached_tree)
install_build_src(args, root, do_run_build_script, for_cache)
install_build_dest(args, root, do_run_build_script, for_cache)
install_extra_trees(args, root, for_cache)
set_root_password(args, root, do_run_build_script, cached_tree)
set_serial_terminal(args, root, do_run_build_script, cached_tree)
set_autologin(args, root, do_run_build_script, cached_tree)
sshkey = setup_ssh(args, root, do_run_build_script, for_cache, cached_tree)
setup_network_veth(args, root, do_run_build_script, cached_tree)
run_postinst_script(args, root, loopdev, do_run_build_script, for_cache)
```
Having the files places in the skeleton tree, it will affect `install_distribution`, although I'm not familiar with how `debootstrap` handles a non-empty treee. Having it in the extra tree or in postinst should not make a difference, as the intervening functions shouldn't affect anything in that regard, so might the problem be overwriting `sources.list`?

**Comment by brpatel12** [comment] 2022-02-02 22:33
> Would that be the minimal reproducer?

Yes, everything you said is correct.

>  what is the state of /etc/apt/sources.list before changing the repositories?

This is just a default single-line entry based on what's specified in `mkosi.default`
```bash
deb http://archive.ubuntu.com/ubuntu focal main restricted universe
```
I guess I technically change that minorly in mine (in addition to adding the other line entries):
```bash
deb http://us.archive.ubuntu.com/ubuntu/ focal main restricted universe
deb http://us.archive.ubuntu.com/ubuntu/ focal-updates main restricted universe
deb http://us.archive.ubuntu.com/ubuntu/ focal-backports main restricted universe
deb http://security.ubuntu.com/ubuntu focal-security main restricted universe
```
- As for using `/etc/apt/sources.list.d/` instead, this seems to also work.

I have a few more data points. So let's ignore the `sources.list` example. Instead let's say I'm trying to add a `yaml` config to `/etc/netplan`. I run into the same issues here (including when I don't even overwrite an existing config file).
- by default, `/etc/netplan/` exists and isn't populated (when I have `Packages=ubuntu-minimal` specified which includes `netplan.io`)
- if I add a config file (`/etc/netplan/01-network.yaml`) via `mkosi.extra` --> I run into systemd issues on boot.
- if I add the exact same file via the following (to `mkosi.postinst`), boot is successful. Any ideas why that would happen? I'd prefer to utilize `mkosi.extra` as it will lead to more maintainable code. I'm sure I could just add the files to `mkosi.extra/<file>` and then `mv` it in the `mkosi.postinst` script `mv /<file> /etc/netplan/`

```bash
#!/bin/bash
set -euo pipefail

cat <<EOF > /etc/netplan/01-netcfg.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    ens3:
      dhcp4: true
      dhcp6: true
EOF
```

**Comment by behrmann** [comment] 2022-02-03 11:42
The only reason for this failing, that I can see, would be something going wrong in `copy_path` or `copy_file`. Comparing `mkosi.extra` and `mkosi.postinst` do the resulting files differ in any way (content, owner, permissions)?

**Comment by wadimklincov** [comment] 2022-02-03 19:10
I had the same issue and was able to reproduce it. With a file in `mkosi.skeleton` the permissions were `600`. After moving it into `mkosi.postinst` they were `644`. Content and owner were they same, though.

**Comment by brpatel12** [comment] 2022-02-03 19:28
File contents the same across all the following - looks like nothing changes (owner/perms) when I use `mkosi.extra` vs `mv`ing the file during `mkosi.postinst`

Config: `mkosi.extra/01-netcfg.yaml`
Permissions:
```bash
# original file
brpatel@bergie:~/mkosi$ ll mkosi.extra/01-netcfg.yaml 
-rw-r--r-- 1 brpatel brpatel 102 Feb  2 14:09 mkosi.extra/01-netcfg.yaml
```
```bash
# mkosi.postinst
ls -lrtah /01-netcfg.yaml
mv /01-netcfg.yaml /etc/netplan/
ls -lrtah /etc/netplan/

# output when building
-rw-r--r-- 1 root root 102 Feb  2 14:09 /01-netcfg.yaml
total 12K
-rw-r--r--  1 root root  102 Feb  2 14:09 01-netcfg.yaml
drwxr-xr-x 54 root root 4.0K Feb  3 11:16 ..
drwxr-xr-x  2 root root 4.0K Feb  3 11:16 .
```

Config: `mkosi.extra/etc/netplan/01-netcfg.yaml`
Permissions:
```bash
# original file same as above
```
```bash
# mkosi.postinst
ls -lrtah /etc/netplan/

# output when building
total 12K
drwxr-xr-x  2 root root 4.0K Feb  3 11:21 .
-rw-r--r--  1 root root  102 Feb  3 11:21 01-netcfg.yaml
drwxr-xr-x 54 root root 4.0K Feb  3 11:27 ..
```

**Comment by behrmann** [comment] 2022-02-04 09:46
@wadimklincov Curious. My guess is that this would somehow run into some edge case where `shutil.copystat` falls back to a noop for the chown. If you were able to reproduce it, do you still have the reproducer?

@brpatel12 Is my understanding correct, that with the above example the resulting netplan file has the same owner and permissions in both cases and one image boots and the other doesn't?

**Comment by wadimklincov** [comment] 2022-02-04 13:11
@behrmann I still have the offending image, yes.

Since my umask is set to 0077, setting the permissions of `mkosi.skeleton` from 700 to 755 fixes the issue for me. Sounds really strange, especially since the target rootfs looks fine to me.

**Comment by brpatel12** [comment] 2022-02-04 18:21
I started from a fresh working directory and am no longer running into this problem, can't for the life of me reproduce it with the same minimal examples. I have attached a non-minimal example from my last successful build.
 
```bash
brpatel@bergie:~/ubuntu_image$ tree
.
├── mkosi.default
├── mkosi.extra
│   └── etc
│       ├── apt
│       │   └── sources.list.d
│       │       └── ubuntu-standard.list
│       └── netplan
│           └── 01-netcfg.yaml
├── mkosi.output
│   ├── test_1.raw
│   └── test_1.raw.manifest
└── mkosi_postinst.sh
```

I'm beyond confused as to why. I think it may be since I started from a new working directory with no prior-failing runs, but that's a gut feeling with no concrete proof (I'm not using mkosi.cache).
```bash
brpatel@bergie:~/ubuntu_image$ tree -ad
.
├── mkosi.extra
│   └── etc
│       ├── apt
│       │   └── sources.list.d
│       └── netplan
└── mkosi.output
    ├── .mkosi-60vb_0xj
    │   └── partial  [error opening dir]
    ├── .mkosi-gpeujcdt
    │   └── partial  [error opening dir]
    ├── .mkosi-lishgtmq
    │   └── partial  [error opening dir]
    └── .mkosi-x03a9fhj
        └── partial  [error opening dir]
```
\# mkosi.postinst
```bash
#!/bin/bash
set -euo pipefail

run_apt_updates() {
  apt-get -y update
  apt-get -y upgrade

  apt-get install -y --no-install-recommends \
    linux-image-generic-hwe-20.04 \
    linux-headers-generic-hwe-20.04 \
    linux-generic-hwe-20.04

  apt-get -y update
  apt-get -y upgrade
}

install_nvidia_drivers() {
  apt-get install -y --no-install-recommends \
    nvidia-driver-470 \
    xserver-xorg-video-nvidia-470
  apt-get -y update
}

main() {
  run_apt_updates
  install_nvidia_drivers
}

export DEBIAN_FRONTEND=noninteractive

main "$@"
```
\# mkosi.default
```bash
[Distribution]
Distribution=ubuntu
Release=focal
Repositories=main,restricted,universe
Architecture=x86_64

[Output]
Format=gpt_ext4
ManifestFormat=json
OutputDirectory=mkosi.output
ImageId=test
ImageVersion=1
Bootable=yes
BootProtocols=uefi

[Content]
WithNetwork=yes
Packages=
  ubuntu-minimal                  # (metapackages): Minimal core of Ubuntu

CleanPackageMetadata=auto
Password=test
PostInstallationScript=mkosi_postinst.sh

[Partitions]
RootSize=4G
ESPSize=100M
```

**Comment by behrmann** [comment] 2022-02-04 18:32
Interesting Heisenbug. I'll close this issue then. If it happens again, let us know. :)

**Closed by behrmann** 2022-02-04 18:32 UTC

**Comment by wadimklincov** [comment] 2022-02-05 11:51
Sorry for bumping a closed issue, I can also create a new one if desired! 

I checked the code and saw that [copy_path](https://github.com/systemd/mkosi/blob/main/mkosi/__init__.py#L633) does a `shutil.copystat` call and copies the permissions from e.g. `mkosi.skeleton` to `root` and that seems to be the issue. Removing the `copystat` call fixes it. Alternatively fixing the permissions after all trees were copied is with `root.chmod(0o755)` works as well.

If those fixes don't make sense, at least a warning (akin to `mkosi.passphrase` having open permissions) or a documentation entry would be great. Otherwise it's hard to figure why the system doesn't boot!

**Comment by behrmann** [comment] 2022-02-05 14:02
@wadimklincov In that context I think I understand your previous comment. Was your assumption, that files in `mkosi.skeleton` (or `mkosi.extra`) would be written with your users umask? The intention of `copy_path` (and `copy_file`) is to preserve the permissions it finds (it can't preserve uid/gid, which is documented, though) and this is parallel to untaring `mkosi.skeleton.tar`, which would also just dump the files with the permissions it finds in the tar. If that is unclear, we should add it to the docs.

**Comment by wadimklincov** [comment] 2022-02-05 17:31
@behrmann Not quite! The files are totally fine, the issue is only with the `mkosi.skeleton` directory (and probably `mkosi.extra`) itself.
When those directories have access permissions `0o700`, then that `shutil.copystat` call will override the access permissions of the `root` directory. And if the image is created with `root` having only `0o700` permissions, then that will lead to this broken image, where systemd jobs are failing and some other things don't work (e.g. `su - user`).

So for me just changing the `mkosi.skeleton` permissions from `0o700` to `0o755` (i.e. `chmod 755 mkosi.skeleton`) creates a working image. And the reverse should create a non-working image.

Sorry, I hope I was able to explain it a bit better! I can also upload both images if you like or can't reproduce it yourself.

I'm not seeing why `root` having `0o700` permissions creates a non-working image down the line, so maybe I'm overlooking something super obvious. But this is just the behavior I can always reproduce.
