### ISSUE TITLE
Ubuntu apt upgrade in postinst causing issues for install_unified_kernel

### ISSUE THREAD

**Issue by dellgreen** [systemd/mkosi#431] opened 2020-06-11 18:03 UTC
As part of a v5 build i was upgrading the ubuntu packages as part of my postinst file. This seemed to work well. However after I tested using master branch today, this is causing the build to fail as a latter phase after the postsint script is ran is failing because dracut is removed as part of the upgrade process. Seemed to be related to the install_unified_kernel function.

```
Traceback (most recent call last):
  File "./tools/mkosi/mkosi", line 5083, in <module>
    main()
  File "./tools/mkosi/mkosi", line 5077, in main
    run_verb(a)
  File "./tools/mkosi/mkosi", line 5054, in run_verb
    build_stuff(args)
  File "./tools/mkosi/mkosi", line 4878, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "./tools/mkosi/mkosi", line 4711, in build_image
    install_unified_kernel(args, workspace.name, do_run_build_script, for_cache, root_hash)
  File "./tools/mkosi/mkosi", line 3098, in install_unified_kernel
    run_workspace_command(args, workspace, *dracut)
  File "./tools/mkosi/mkosi", line 1340, in run_workspace_command
    run(cmdline, check=True)
  File "./tools/mkosi/mkosi", line 89, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemd-nspawn', '--quiet', '--directory=/var/tmp/mkosi-iu5ehmp7/root', '--uuid=92d5e5eff3684bed81c86f0b4a2afb30', '--machine=mkosi-28179d02471947bba34553ecabe924b3', '--as-pid2', '--register=no', '--bind=/var/tmp/mkosi-iu5ehmp7/var-tmp:/var/tmp', '--setenv=SYSTEMD_OFFLINE=1', '--private-network', '--', '/usr/bin/dracut', '-v', '--no-hostonly', '--uefi', '--uefi-stub', '/usr/lib/systemd/boot/efi/linuxx64.efi.stub', '--kver', '5.3.0-59-generic', '--kernel-cmdline', 'rhgb quiet selinux=0 audit=0 rw', '-i', '/usr/lib/systemd/system/systemd-volatile-root.service', '/usr/lib/systemd/system/systemd-volatile-root.service', '-i', '/usr/lib/systemd/systemd-volatile-root', '/usr/lib/systemd/systemd-volatile-root', '-i', '/usr/lib/systemd/systemd-veritysetup', '/usr/lib/systemd/systemd-veritysetup', '-i', '/usr/lib/systemd/system-generators/systemd-veritysetup-generator', '/usr/lib/systemd/system-generators/systemd-veritysetup-generator', '-i', '/usr/bin/systemd-repart', '/usr/bin/systemd-repart', '-i', '/usr/lib/systemd/system/systemd-repart.service', '/usr/lib/systemd/system/systemd-repart.service', '-i', '/usr/lib/systemd/system/initrd-root-fs.target.wants/systemd-repart.service', '/usr/lib/systemd/system/initrd-root-fs.target.wants/systemd-repart.service', '-i', '/usr/lib/systemd/system-generators/systemd-debug-generator', '/usr/lib/systemd/system-generators/systemd-debug-generator', '--add-drivers', 'squashfs', '--add', 'qemu', '/efi/EFI/Linux/linux-5.3.0-59-generic.efi']' returned non-zero exit status 1.
```
In testing I managed to fix this by use apt to hold the dracut package to prevent it from being removed, however a new error was hit shortly after.

```
Traceback (most recent call last):
  File "/opt/mkosi/mkosi", line 5083, in <module>
    main()
  File "/opt/mkosi/mkosi", line 5077, in main
    run_verb(a)
  File "/opt/mkosi/mkosi", line 5054, in run_verb
    build_stuff(args)
  File "/opt/mkosi/mkosi", line 4878, in build_stuff
    raw, tar, root_hash = build_image(args, workspace, do_run_build_script=False, cleanup=True)
  File "/opt/mkosi/mkosi", line 4691, in build_image
    run_postinst_script(args, workspace.name, do_run_build_script, for_cache)
  File "/opt/mkosi/mkosi", line 2427, in run_postinst_script
    run_workspace_command(args, workspace, "/root/postinst", verb, network=args.with_network)
  File "/opt/mkosi/mkosi", line 1340, in run_workspace_command
    run(cmdline, check=True)
  File "/opt/mkosi/mkosi", line 89, in run
    return subprocess.run(cmdline, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['systemd-nspawn', '--quiet', '--directory=/var/tmp/mkosi-ocmjeq89/root', '--uuid=4f67194b887e44cf99675404594bfdda', '--machine=mkosi
-530d83aa8811477789c0f2adc0848390', '--as-pid2', '--register=no', '--bind=/var/tmp/mkosi-ocmjeq89/var-tmp:/var/tmp', '--setenv=SYSTEMD_OFFLINE=1', '--bind-ro=/etc/resolv.con
f', '--', '/root/postinst', 'final']' returned non-zero exit status 127.
```

Should I not be upgrading the packages as part of the mkosi build process?

**Comment by fernandolobato** [comment] 2020-06-12 16:52
Two quick questions: 

1. Were you just running "apt update" in you post install script?

2. Second, if its possible could you share the error message, it appears higher up in the output, before the image description.  (For both failures)

**Comment by dellgreen** [comment] 2020-06-12 17:06
1. Running apt-update is fine as it is only updating the source index files, its apt upgrade  and apt autoremove that is causing the package manager to remove dracut. I have removed all this code now into my secondary  systemd-nspawn post-process part of the build pipeline that runs after mkosi has completed.

2. Unfortunately I don't have that info at the moment, when i get a chance i'll rewind to before making my changes and get a fuller error output

**Comment by dellgreen** [comment] 2020-06-18 11:32
Apologies for the delay, full build log is attached:

[build.log](https://github.com/systemd/mkosi/files/4798197/build.log)

**Comment by DaanDeMeyer** [comment] 2020-08-01 15:42
dracut is explicitly installed by mkosi. Why would autoremove uninstall it?

**Comment by DaanDeMeyer** [comment] 2020-08-08 10:36
With the following steps, I wasn't able to reproduce the issue:

```
git clone https://github.com/DaanDeMeyer/mkosi --branch arch-kernel-install-hooks
printf "apt update\napt upgrade\napt autoremove\n" > mkosi.postinst
chmod +x mkosi.postinst
./mkosi -d ubuntu --bootable --with-network -f
```

It does reveal that we're running dracut way too much during ubuntu/debian installs but that's another issue. I didn't test with master but that branch should be merged soon so I'm going to close this as not reproducible anymore. Feel free to leave a comment if this is still an issue for you. Also include detailed reproduce instructions then if you can.

**Closed by DaanDeMeyer** 2020-08-08 10:36 UTC
Labels: bug, needs-reporter-feedback

**Comment by dellgreen** [comment] 2020-08-08 11:50
Ok thanks, when I get a chance I'll retest

**Comment by DaanDeMeyer** [comment] 2020-08-08 11:54
There's also mkosi.prepare scripts now which might be a better place to run apt since you won't need --with-network and it runs right after distro installation.

**Comment by dellgreen** [comment] 2020-08-08 12:05
Cool thanks, i'll take a look at the also
