### ISSUE TITLE
Firmware files not included in initrd

### ISSUE THREAD

**Issue by septatrix** [systemd/mkosi#2399] opened 2024-02-18 00:34 UTC
Even though the initrd seems to be generated correctly (i.e. the log does not mention that the firmware files have not been found) there are no firmware files in the generated initrd. When generating an image with [iwlwifi-mvm-firmware](https://packages.fedoraproject.org/pkgs/linux-firmware/iwlwifi-mvm-firmware/) I get several `iwlwifi 0000:00:14.3: Direct firmware load for iwlwifi-QuZ-a0-hr-b0-63.ucode failed with error -2` messages in dmesg, one for every firmware version. I manually booted into the initrd `rd.rescue` and to my surprise the whole `/usr/lib/firmware` directory was empty.

I have `iwlwifi-mvm-firmware` listed as part of my normal packages and otherwise no options set for initrd. Based on my understanding this should result in all kernel modules (and their required firmware files) being included in the initrd. I even hooked into the initrd generation code and saved all files passed to the function in a file. The firmware files are listed in the initrd generated in `build_kernel_modules_initrd()` but not the final one.

**Comment by DaanDeMeyer** [comment] 2024-02-18 06:06
Isn't this a duplicate of #2334?

**Comment by septatrix** [comment] 2024-02-18 11:25
That issue does not seem to be about the initrd and also uses `KernerModulesInclude/-Exclude=` which I do not though they could certainly be related. Also in my case all of `/usr/lib/firmware` is missing instead on only threat one .pnvm.xz file.

**Comment by DaanDeMeyer** [comment] 2024-02-18 14:21
@septatrix Can you provide a reproducer?

**Closed** 2024-02-18 17:50 UTC
Labels: bug
