### ISSUE TITLE
Fedora images seem to fail to build on Fedora hosts (in the systemd repository)

### ISSUE THREAD

**Issue by evverx** [systemd/mkosi#2739] opened 2024-05-31 20:38 UTC
### mkosi commit the issue has been seen with

main

### Used host distribution

Fedora 40

### Used target distribution

rawhide

### Linux kernel version used

6.8.10-300.fc40.x86_64

### CPU architectures issue was seen on

None

### Unexpected behaviour you saw

`mkosi build` seems to fail to build Fedora images on Fedora hosts when it's run in https://github.com/systemd/systemd

### Used mkosi config

```ini
It is from https://github.com/systemd/systemd
```

### mkosi output

```sh
mkosi build
...
‣  Running prepare script /home/vagrant/systemd-mkosi/mkosi.images/system/mkosi.conf.d/10-centos-fedora/mkosi.prepare…
Last metadata expiration check: 0:05:11 ago on Fri May 31 20:23:20 2024.
Package util-linux-2.40.1-1.fc41.x86_64 is already installed.
Package util-linux-core-2.40.1-1.fc41.x86_64 is already installed.
Package coreutils-9.5-1.fc41.x86_64 is already installed.
Package dbus-1:1.14.10-3.fc40.x86_64 is already installed.
Package grep-3.11-8.fc41.x86_64 is already installed.
Package kbd-2.6.4-3.fc40.x86_64 is already installed.
Package kmod-31-5.fc40.x86_64 is already installed.
Package libidn2-2.3.7-1.fc40.x86_64 is already installed.
Package libidn2-2.3.7-1.fc40.x86_64 is already installed.
Package kmod-libs-31-5.fc40.x86_64 is already installed.
Package kmod-libs-31-5.fc40.x86_64 is already installed.
Package openssl-libs-1:3.2.1-6.fc41.x86_64 is already installed.
Error: 
 Problem: package sdubby-1.0-8.fc41.noarch from fedora conflicts with grubby provided by grubby-8.40-75.fc40.x86_64 from fedora
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
‣ "/work/prepare final" returned non-zero exit code 123.
‣  (Fixing ownership of package manager cache directory)
```

**Comment by DaanDeMeyer** [comment] 2024-05-31 21:04
You chose a bit of an unfortunate time as the rpm 4.20 alpha has just been added to Fedora rawhide and this is likely breakage caused by that (it's caused a few other issues as well). If you set `Release=40` in mkosi.local.conf (or `--release 40` on the mkosi command line), you should get further. I'll report an issue to rpm after debugging a bit more.

**Comment by evverx** [comment] 2024-05-31 21:07
> If you set Release=40 in mkosi.local.conf 

It fails too with
```sh
‣  Running prepare script /home/vagrant/systemd-mkosi/mkosi.images/system/mkosi.conf.d/10-centos-fedora/mkosi.prepare…
Last metadata expiration check: 0:05:08 ago on Fri May 31 20:55:39 2024.
Package util-linux-2.40.1-1.fc40.x86_64 is already installed.
Package util-linux-core-2.40.1-1.fc40.x86_64 is already installed.
Package coreutils-9.4-6.fc40.x86_64 is already installed.
Package dbus-1:1.14.10-3.fc40.x86_64 is already installed.
Package grep-3.11-7.fc40.x86_64 is already installed.
Package kbd-2.6.4-3.fc40.x86_64 is already installed.
Package kmod-31-5.fc40.x86_64 is already installed.
Package libidn2-2.3.7-1.fc40.x86_64 is already installed.
Package libidn2-2.3.7-1.fc40.x86_64 is already installed.
Package kmod-libs-31-5.fc40.x86_64 is already installed.
Package kmod-libs-31-5.fc40.x86_64 is already installed.
Package openssl-libs-1:3.2.1-2.fc40.x86_64 is already installed.
Error: 
 Problem: package sdubby-1.0-8.fc40.noarch from fedora conflicts with grubby provided by grubby-8.40-75.fc40.x86_64 from fedora
  - conflicting requests
(try to add '--allowerasing' to command line to replace conflicting packages or '--skip-broken' to skip uninstallable packages)
‣ "/work/prepare final" returned non-zero exit code 123.
‣  (Fixing ownership of package manager cache directory)

```

**Comment by DaanDeMeyer** [comment] 2024-05-31 21:19
@evverx This is actually a bug in dnf. Can you install `dnf5`, that does the right thing. I'll land a work around in systemd to work around the dnf bug.

**Comment by DaanDeMeyer** [comment] 2024-05-31 21:25
@evverx https://github.com/systemd/systemd/pull/33135

**Comment by DaanDeMeyer** [comment] 2024-05-31 21:47
Fix was merged, closing this

**Closed by DaanDeMeyer** 2024-05-31 21:47 UTC
Labels: bug
