### ISSUE TITLE
Builing Archlinux arm64 on amd64 fails

### ISSUE THREAD

**Issue by s3rj1k** [systemd/mkosi#3130] opened 2024-10-16 14:35 UTC
### mkosi commit the issue has been seen with

mkosi 24.3

### Used host distribution

Archlinux [amd64]

### Used target distribution

Archlinux [arm64]

### Linux kernel version used

6.6.56-1-lts

### CPU architectures issue was seen on

x86_64

### Unexpected behaviour you saw

Build is failing on pacman bootstrap

### Used mkosi config

```ini
[Distribution]
Architecture=arm64
Distribution=arch

[Output]
Format=disk
Output=arch.vm

[Content]
Autologin=yes
Bootable=yes
Bootloader=uki
WithNetwork=yes
Packages=
	archlinux-keyring
	base
	linux-lts
	linux-firmware
	nano
	systemd
	udev

[Validation]
Checksum=yes

[Host]
QemuMem=6G
QemuSmp=2
QemuVsock=yes
```

### mkosi output

```sh
File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 60, in uncaught_exception_handler
    yield
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 101, in fork_and_wait
    target(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 4761, in run_build
    build_image(Context(args, config, workspace=workspace, resources=resources, package_dir=package_dir))
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 3915, in build_image
    install_distribution(context)
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 152, in install_distribution
    context.config.distribution.install(context)
  File "/usr/lib/python3.12/site-packages/mkosi/distributions/__init__.py", line 114, in install
    return self.installer().install(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkosi/distributions/arch.py", line 41, in install
    cls.install_packages(context, ["filesystem"], apivfs=False)
  File "/usr/lib/python3.12/site-packages/mkosi/distributions/arch.py", line 45, in install_packages
    Pacman.invoke(
  File "/usr/lib/python3.12/site-packages/mkosi/installer/pacman.py", line 167, in invoke
    return run(
           ^^^^
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 150, in run
    with spawn(
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 352, in spawn
    raise subprocess.CalledProcessError(returncode, cmdline)
subprocess.CalledProcessError: Command '['pacman', '--root=/buildroot', '--logfile=/dev/null', '--dbpath=/var/lib/pacman', '--cachedir=/var/cache/pacman/mkosi', '--cachedir=/var/cache/pacman/pkg', '--hookdir=/buildroot/etc/pacman.d/hooks', '--arch', 'aarch64', '--color', 'auto', '--noconfirm', '--sync', '--needed', '--assume-installed', 'initramfs', 'filesystem']' returned non-zero exit status 1.
```

**Comment by behrmann** [comment] 2024-10-16 14:45
Can you put the full output in a gist and also try with current main?

**Comment by s3rj1k** [comment] 2024-10-16 14:48
> full output

```
arm64 $ mkosi --debug build
‣ Including configuration file /home/s3rj1k/Desktop/tiny-vms/efi/mkosi/arch/arm64/mkosi.conf
‣ + timedatectl show -p Timezone --value
‣ + timedatectl show -p Timezone --value
‣ + findmnt --target / --output FSTYPE --noheadings
‣ Acquiring lock on /tmp/mkosi-uidmap-lock-b_bg0nus
‣ Acquired lock on /tmp/mkosi-uidmap-lock-b_bg0nus
‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock-b_bg0nus newuidmap 51403 0 100000 65436 65436 1000 1 65437 165437 99
‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock-b_bg0nus newgidmap 51403 0 100000 65436 65436 1000 1 65437 165437 99
‣ + stat --file-system --format %T /home/s3rj1k/.cache/mkosi/mkosi-workspace-8ap2cozc
‣ Syncing package manager metadata for default image
‣ Acquiring lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman
‣ Acquired lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman
‣ Acquiring lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman
‣ Acquired lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman
‣ + pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch aarch64 --color auto --noconfirm --sync --refresh
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 alarm is up to date
‣ + rm -rf -- /home/s3rj1k/.cache/mkosi/mkosi-workspace-8ap2cozc
‣ Acquiring lock on /tmp/mkosi-uidmap-lock-6iqyyyvx
‣ Acquired lock on /tmp/mkosi-uidmap-lock-6iqyyyvx
‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock-6iqyyyvx newuidmap 51484 0 100000 65436 65436 1000 1 65437 165437 99
‣ + flock --exclusive --close /tmp/mkosi-uidmap-lock-6iqyyyvx newgidmap 51484 0 100000 65436 65436 1000 1 65437 165437 99
‣ Building default image
‣ + /usr/bin/systemd-repart --version
‣ + stat --file-system --format %T /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv
‣ Acquiring lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman
‣ Acquired lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman
‣ Acquiring lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman
‣ Acquired lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman
‣ + cp --version
‣ + cp --recursive --no-dereference --preserve=mode,links --reflink=auto --copy-contents '/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman' /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/root/var/cache/pacman --keep-directory-symlink --no-target-directory
‣ + cp --version
‣ + cp --recursive --no-dereference --preserve=mode,links --reflink=auto --copy-contents '/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman' /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/root/var/lib/pacman --keep-directory-symlink --no-target-directory
‣  Installing Arch
‣ + pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch aarch64 --color auto --noconfirm --sync --needed --assume-installed initramfs filesystem
resolving dependencies...
looking for conflicting packages...

Packages (2) iana-etc-20240814-1  filesystem-2024.04.07-1

Total Installed Size:  4.01 MiB

:: Proceed with installation? [Y/n] 
(2/2) checking keys in keyring                                                                          [#############################################################] 100%
downloading required keys...
error: keyring is not writable
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
‣ "bwrap --die-with-parent --proc /proc --setenv SYSTEMD_OFFLINE 1 --unsetenv TMPDIR --dir /tmp --dir /var/tmp --unshare-ipc --dev /dev --symlink usr/bin /bin --symlink usr/bin /sbin --symlink usr/lib /lib --symlink usr/lib /lib64 --setenv PATH /scripts:/home/s3rj1k/.go/bin:/usr/local/bin:/usr/bin --uid 0 --gid 0 --cap-add ALL --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/root /buildroot --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/pkgmngr/etc /etc --ro-bind /etc/alternatives /etc/alternatives --ro-bind /etc/ca-certificates /etc/ca-certificates --ro-bind /etc/pacman.d/gnupg /etc/pacman.d/gnupg --ro-bind /etc/pki /etc/pki --bind /etc/resolv.conf /etc/resolv.conf --ro-bind /etc/ssl /etc/ssl --ro-bind /etc/ca-certificates/extracted/tls-ca-bundle.pem /proxy.cacert --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/repository /repository --ro-bind /usr /usr --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/root/var/cache/pacman /var/cache/pacman --ro-bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/repository /var/cache/pacman/mkosi --bind '/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman/pkg' /var/cache/pacman/pkg --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/root/var/lib/pacman /var/lib/pacman --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/pkgmngr/var/log /var/log --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv/tmp/mkosi-var-tmp-2386105288a748bc /var/tmp sh -c 'chmod 1777 /tmp && chmod 1777 /dev/shm && chmod 1777 /var/tmp && chmod 755 /etc && exec $0 "$@"' setpgid --foreground -- pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch aarch64 --color auto --noconfirm --sync --needed --assume-installed initramfs filesystem" returned non-zero exit code 1.
‣ + rm -rf -- /home/s3rj1k/.cache/mkosi/mkosi-workspace-7biuemxv
‣  (Fixing ownership of package manager cache directory)
‣ + chown --recursive 65436:65436 '/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman'
‣ + chown --recursive 65436:65436 '/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 60, in uncaught_exception_handler
    yield
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 101, in fork_and_wait
    target(*args, **kwargs)
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 4761, in run_build
    build_image(Context(args, config, workspace=workspace, resources=resources, package_dir=package_dir))
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 3915, in build_image
    install_distribution(context)
  File "/usr/lib/python3.12/site-packages/mkosi/__init__.py", line 152, in install_distribution
    context.config.distribution.install(context)
  File "/usr/lib/python3.12/site-packages/mkosi/distributions/__init__.py", line 114, in install
    return self.installer().install(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/mkosi/distributions/arch.py", line 41, in install
    cls.install_packages(context, ["filesystem"], apivfs=False)
  File "/usr/lib/python3.12/site-packages/mkosi/distributions/arch.py", line 45, in install_packages
    Pacman.invoke(
  File "/usr/lib/python3.12/site-packages/mkosi/installer/pacman.py", line 167, in invoke
    return run(
           ^^^^
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 150, in run
    with spawn(
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/usr/lib/python3.12/site-packages/mkosi/run.py", line 352, in spawn
    raise subprocess.CalledProcessError(returncode, cmdline)
subprocess.CalledProcessError: Command '['pacman', '--root=/buildroot', '--logfile=/dev/null', '--dbpath=/var/lib/pacman', '--cachedir=/var/cache/pacman/mkosi', '--cachedir=/var/cache/pacman/pkg', '--hookdir=/buildroot/etc/pacman.d/hooks', '--arch', 'aarch64', '--color', 'auto', '--noconfirm', '--sync', '--needed', '--assume-installed', 'initramfs', 'filesystem']' returned non-zero exit status 1.
‣ + tput cnorm
‣ + tput smam
```

**Comment by s3rj1k** [comment] 2024-10-16 14:56
> try with current main

same error

@behrmann

**Comment by s3rj1k** [comment] 2024-10-16 15:02
> Could you show the output from that?

```
arm64 $ /home/s3rj1k/Desktop/mkosi/bin/mkosi --debug build
‣ Loading configuration file /home/s3rj1k/Desktop/tiny-vms/efi/mkosi/arch/arm64/mkosi.conf
‣ /home/s3rj1k/Desktop/tiny-vms/efi/mkosi/arch/arm64/mkosi.conf: Setting WithNetwork should be configured in [Build], not [Content].
‣ + /usr/bin/systemd-repart --version
‣ Syncing package manager metadata
‣ Acquiring lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman
‣ Acquired lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman
‣ Acquiring lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman
‣ Acquired lock on /home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman
‣ + pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch aarch64 --color auto --noconfirm --sync --refresh
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 alarm is up to date
‣ + rm -rf -- /work/home/s3rj1k/.cache/mkosi/mkosi-workspace-46dvk3yz
‣ Copying repository metadata
‣ + cp --recursive --no-dereference --preserve=mode,links,timestamps,ownership,xattr --reflink=auto --copy-contents '/work/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman' /work/home/s3rj1k/.cache/mkosi/mkosi-metadata-exntz9q7/cache/pacman --no-target-directory
‣ + cp --recursive --no-dereference --preserve=mode,links,timestamps,ownership,xattr --reflink=auto --copy-contents '/work/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/lib/pacman' /work/home/s3rj1k/.cache/mkosi/mkosi-metadata-exntz9q7/lib/pacman --no-target-directory
‣ Building default image
‣  Installing Arch Linux
‣ + pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch aarch64 --color auto --noconfirm --sync --needed --assume-installed initramfs filesystem
resolving dependencies...
looking for conflicting packages...

Packages (2) iana-etc-20240814-1  filesystem-2024.04.07-1

Total Installed Size:  4.01 MiB

:: Proceed with installation? [Y/n] 
(2/2) checking keys in keyring                                                                          [#############################################################] 100%
downloading required keys...
error: keyring is not writable
error: required key missing from keyring
error: failed to commit transaction (unexpected error)
Errors occurred, no packages were upgraded.
‣ "/usr/bin/python3 -SI /home/s3rj1k/Desktop/mkosi/mkosi/sandbox.py --proc /proc --unsetenv TMPDIR --setenv SYSTEMD_OFFLINE 1 --ro-bind /home/s3rj1k/Desktop/mkosi/mkosi/sandbox.py /sandbox.py --ro-bind /usr /usr --symlink usr/bin /bin --symlink usr/bin /sbin --symlink usr/lib /lib --symlink usr/lib /lib64 --ro-bind /etc/alternatives /etc/alternatives --ro-bind /etc/ld.so.cache /etc/ld.so.cache --dir /var/tmp --dir /var/log --unshare-ipc --dev /dev --ro-bind /etc/resolv.conf /etc/resolv.conf --setenv PATH /scripts:/home/s3rj1k/.go/bin:/usr/local/bin:/usr/bin --ro-bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/sandbox/etc /etc --dir /opt --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/tmp/mkosi-var-tmp-aeac89ff29704b1b /srv --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/tmp/mkosi-var-tmp-87472fc151104a54 /media --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/tmp/mkosi-var-tmp-41ab7920c6ed418a /mnt --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/tmp/mkosi-var-tmp-34e11fdd30844a04 /var --dir /run --dir /tmp --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/tmp/mkosi-var-tmp-2ca0985817804ddf /var/tmp --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/root /buildroot --ro-bind /etc/ca-certificates /etc/ca-certificates --ro-bind /etc/pacman.d/gnupg /etc/pacman.d/gnupg --ro-bind /etc/pki /etc/pki --ro-bind /etc/ssl /etc/ssl --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/repository /repository --bind /home/s3rj1k/.cache/mkosi/mkosi-metadata-exntz9q7/cache/pacman /var/cache/pacman --bind '/home/s3rj1k/.cache/mkosi/arch~rolling~arm64/cache/pacman/pkg' /var/cache/pacman/pkg --bind /home/s3rj1k/.cache/mkosi/mkosi-metadata-exntz9q7/lib/pacman /var/lib/pacman --ro-bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/repository /var/cache/pacman/mkosi --bind /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/root/var/lib/pacman/local /var/lib/pacman/local --become-root --suppress-chown --ro-bind-try /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/root/etc/machine-id /buildroot/etc/machine-id --ro-bind-try /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/root/etc/passwd /etc/passwd --ro-bind-try /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/root/etc/group /etc/group --ro-bind-try /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/root/etc/shadow /etc/shadow --ro-bind-try /home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn/root/etc/gshadow /etc/gshadow --ro-bind /etc/ca-certificates/extracted/tls-ca-bundle.pem /proxy.cacert -- pacman --root=/buildroot --logfile=/dev/null --dbpath=/var/lib/pacman --cachedir=/var/cache/pacman/mkosi --cachedir=/var/cache/pacman/pkg --hookdir=/buildroot/etc/pacman.d/hooks --arch aarch64 --color auto --noconfirm --sync --needed --assume-installed initramfs filesystem" returned non-zero exit code 1.
‣ + rm -rf -- /work/home/s3rj1k/.cache/mkosi/mkosi-workspace-7trvblcn
Traceback (most recent call last):
  File "/home/s3rj1k/Desktop/mkosi/mkosi/run.py", line 64, in uncaught_exception_handler
    yield
  File "/home/s3rj1k/Desktop/mkosi/mkosi/run.py", line 105, in fork_and_wait
    target(*args, **kwargs)
  File "/home/s3rj1k/Desktop/mkosi/mkosi/__init__.py", line 4395, in run_build
    build_image(
  File "/home/s3rj1k/Desktop/mkosi/mkosi/__init__.py", line 3572, in build_image
    install_distribution(context)
  File "/home/s3rj1k/Desktop/mkosi/mkosi/__init__.py", line 210, in install_distribution
    context.config.distribution.install(context)
  File "/home/s3rj1k/Desktop/mkosi/mkosi/distributions/__init__.py", line 130, in install
    return self.installer().install(context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/s3rj1k/Desktop/mkosi/mkosi/distributions/arch.py", line 41, in install
    cls.install_packages(context, ["filesystem"], apivfs=False)
  File "/home/s3rj1k/Desktop/mkosi/mkosi/distributions/arch.py", line 45, in install_packages
    Pacman.invoke(
  File "/home/s3rj1k/Desktop/mkosi/mkosi/installer/pacman.py", line 171, in invoke
    return run(
           ^^^^
  File "/home/s3rj1k/Desktop/mkosi/mkosi/run.py", line 152, in run
    with spawn(
         ^^^^^^
  File "/usr/lib/python3.12/contextlib.py", line 144, in __exit__
    next(self.gen)
  File "/home/s3rj1k/Desktop/mkosi/mkosi/run.py", line 297, in spawn
    raise subprocess.CalledProcessError(returncode, cmdline)
subprocess.CalledProcessError: Command '['pacman', '--root=/buildroot', '--logfile=/dev/null', '--dbpath=/var/lib/pacman', '--cachedir=/var/cache/pacman/mkosi', '--cachedir=/var/cache/pacman/pkg', '--hookdir=/buildroot/etc/pacman.d/hooks', '--arch', 'aarch64', '--color', 'auto', '--noconfirm', '--sync', '--needed', '--assume-installed', 'initramfs', 'filesystem']' returned non-zero exit status 1.
‣ + tput cnorm
‣ + tput smam
```

**Comment by behrmann** [comment] 2024-10-16 16:26
The problem is that you are missing the keys Archlinux ARM keys from your pacman keyring.

While for other package managers it's quite easy to add keys by telling them the path to the key in the repo config, pacman uses GPG rather directly and has a global GPG directory, which makes this all a bit finicky.

Looking at this, we do have a code path to use the `pacman.d/gnupg` directory from a tools tree, so I see three options
1. Install the `archlinuxarm-keyring` on your system and add it to your pacman keyring (probably not ideal)
2. Configure pacman with a sandbox tree to use a different `GPGDir=`, that you build yourself (might be difficult, `pacman-key` is not very forthcoming when not working as root)
3. Build a (regular x86_64) tools tree and download the `archlinuxarm-keyring` package and populate the keyring into its pacman config with a postinst script.

I'd go for option 3 in your case. 
 
The most basic tools tree can be had for a simple `mkosi --directory "" --include mkosi-tools --output mkosi.tools` on the commandline, but you will need to get the `archlinuxarm-keyring` package in there, probably by downloading it out of band and using `PackageDirectories=` / `--package-directory=`.

**Comment by s3rj1k** [comment] 2024-10-16 16:37
@behrmann Can rootfs image from https://archlinuxarm.org/platforms/armv8/generic be somehow reused?

**Comment by behrmann** [comment] 2024-10-16 20:07
Sure, if you can boot it in qemu running the above mkosi config should just work™.

**Comment by s3rj1k** [comment] 2024-10-16 20:09
> boot it in qemu

I would like to avoid that very much :)

I am looking for something that can be automated in a consistent way.

**Comment by behrmann** [comment] 2024-10-16 20:52
> I would like to avoid that very much :)

How else would you use foreign binaries?

> I am looking for something that can be automated in a consistent way.

Haven't tried it, but making a tool tree should be easiest, similar to this maybe
```bash
curl -O http://mirror.archlinuxarm.org/aarch64/core/archlinuxarm-keyring-20240419-1-any.pkg.tar.xz
mkdir alarmrepo
mv archlinuxarm-keyring-20240419-1-any.pkg.tar.xz alarmrepo
cat >alarminit.sh <<EOF
#!/bin/bash
pacman-key --init
pacman-key --populate archlinuxarm
EOF
chmod +x alarminit.sh
mkosi mkosi --directory "" --include mkosi-tools --package-directory alarmrepo --package archlinuxarm-keyring --postinst-script alarminit.sh --output mkosi.tools
```

**Comment by s3rj1k** [comment] 2024-10-18 09:52
I've ended up doing all the things using [docker](https://github.com/s3rj1k/tiny-vms/tree/main/efi/docker/arch/arm64)

**Comment by DaanDeMeyer** [comment] 2024-10-21 18:40
Nothing we can help with, the GPG keys (or keyring in Arch's case) have to be available on the host system from which the build is done and the arch linux arm keyring is not packaged anywhere I think except on arch linux arm itself. This is something to be fixed in arch linux arm and not something we can work around in mkosi.

**Closed by DaanDeMeyer** 2024-10-21 18:40 UTC
Labels: bug
