### ISSUE TITLE
openSUSE can't be built with v11

### ISSUE THREAD

**Issue by evverx** [systemd/mkosi#861] opened 2021-11-25 03:27 UTC
Trying to bump the mkosi action from v10 to v11 in https://github.com/systemd/systemd/pull/21505, the systemd CI discovered that openSUSE can't be built:
```
2021-11-24T15:41:28.8020117Z ‣  (Detaching /dev/loop4)
2021-11-24T15:41:28.8020511Z Traceback (most recent call last):
2021-11-24T15:41:28.8021002Z   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
2021-11-24T15:41:28.8021699Z     return _run_code(code, main_globals, None,
2021-11-24T15:41:28.8022373Z   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
2021-11-24T15:41:28.8022844Z     exec(code, run_globals)
2021-11-24T15:41:28.8024160Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 32, in <module>
2021-11-24T15:41:28.8024941Z     main()
2021-11-24T15:41:28.8025982Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/__main__.py", line 26, in main
2021-11-24T15:41:28.8026496Z     run_verb(a)
2021-11-24T15:41:28.8027522Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7809, in run_verb
2021-11-24T15:41:28.8028389Z     manifest = build_stuff(args)
2021-11-24T15:41:28.8029310Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 7219, in build_stuff
2021-11-24T15:41:28.8029910Z     image = build_image(args, root, do_run_build_script=True)
2021-11-24T15:41:28.8030654Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 6965, in build_image
2021-11-24T15:41:28.8031297Z     install_distribution(args, root, do_run_build_script, cached_tree)
2021-11-24T15:41:28.8032128Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 3111, in install_distribution
2021-11-24T15:41:28.8033948Z     install[args.distribution](args, root, do_run_build_script)
2021-11-24T15:41:28.8034735Z   File "/usr/lib/python3.8/contextlib.py", line 75, in inner
2021-11-24T15:41:28.8035329Z     return func(*args, **kwds)
2021-11-24T15:41:28.8036720Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/__init__.py", line 2991, in install_opensuse
2021-11-24T15:41:28.8038339Z     run(["zypper", "--root", root, "addrepo", "-ck", release_url, "repo-oss"])
2021-11-24T15:41:28.8039468Z   File "/usr/local/lib/python3.8/dist-packages/mkosi/backend.py", line 699, in run
2021-11-24T15:41:28.8040314Z     return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
2021-11-24T15:41:28.8041055Z   File "/usr/lib/python3.8/subprocess.py", line 516, in run
2021-11-24T15:41:28.8041904Z     raise CalledProcessError(retcode, process.args,
2021-11-24T15:41:28.8043563Z subprocess.CalledProcessError: Command '['zypper', '--root', '/var/tmp/mkosi-9h5rlh3u/root', 'addrepo', '-ck', 'http://download.opensuse.org/tumbleweed/repo/oss/', 'repo-oss']' returned non-zero exit status 4.
```
According to https://github.com/systemd/systemd/pull/21505#issuecomment-978017393 there is something wrong with `zipper`
```
Target initialization failed:
Failed to cache rpm database (1).
```

**Comment by evverx** [comment] 2021-11-25 03:41
FWIW as long as openSUSE isn't integrated into the mkosi CI I don't think it should be in the systemd CI either so I'd just drop it there and switch to v11

**Comment by Werkov** [comment] 2021-11-25 14:17
I'm looking into this. I suspect the culprit might be bumped RPM that is used by zypper in openSUSE builds. Testing the systemd PRs against openSUSE TW is where I see most value.

(To optimize my efforts, I didn't actively pursue `opensuse` in mkosi CI (reduce noise and deal with issues that propagate only to systemd). I see now it may be useful to catch issue early (not sure about the noise yet).)

**Comment by evverx** [comment] 2021-11-25 14:44
I'm not sure what kind of noise should be reduced but if it's too noisy to be enabled here I don't think it should be moved to the systemd CI either because as far as I can tell basically all the issues propagate to systemd and the systemd maintainers have to open PRs like https://github.com/systemd/systemd/pull/21052.

**Comment by mrc0mmand** [comment] 2022-01-01 21:56
Oh well. The current issue seems to be in `libsolv`. As @Werkov already pointed out (https://github.com/systemd/mkosi/pull/862#issuecomment-980220401), it works with RPM 4.16 but it doesn't with RPM 4.17 - that's because there's a workaround in `libsolv` which explicitly matches the 4.16 version - https://github.com/openSUSE/libsolv/commit/c78a330a27bb3844b97e694552efc4a373cf217b. Looks like it needs to be done for 4.17 as well.

```
$ sudo zypper -vv --root /var/tmp/hello-world update
Verbosity: 2
Initializing Target
Target initialization failed:
Failed to cache rpm database (1).
History:
 - 'rpmdb2solv' '-r' '/var/tmp/hello-world' '-X' '-p' '/var/tmp/hello-world/etc/products.d' '-o' '/var/tmp/hello-world/var/cache/zypp/solv/@System/solvjNSBOh'
warning: using dummy database, installs not possible
rpmdb2solv: no error
```

Now let's build latest `libsolv` with a custom patch:

```diff
diff --git a/ext/repo_rpmdb_librpm.h b/ext/repo_rpmdb_librpm.h
index 3f9798c2..e1b30a0f 100644
--- a/ext/repo_rpmdb_librpm.h
+++ b/ext/repo_rpmdb_librpm.h
@@ -136,7 +136,7 @@ opendbenv(struct rpmdbstate *state)
       return 0;
     }
 #ifndef HAVE_RPMDBNEXTITERATORHEADERBLOB
-  if (!strcmp(RPMVERSION, "4.16.0"))
+  if (!strcmp(RPMVERSION, "4.16.0") || !strcmp(RPMVERSION, "4.17.0"))
     set_db_backend();
 #endif
   if (rpmtsOpenDB(ts, O_RDONLY))
```

```
$ git clone https://github.com/OpenSUSE/libsolv
$ git apply
<the patch above>
$ cd libsolv
$ mkdir build
$ cd build
$ cmake -DENABLE_RPMMD=1 -DENABLE_RPMDB=1 -DENABLE_RPMDB_BYRPMHEADER=1 -DENABLE_HELIXREPO=1 ..
$ sudo make install
```

```
$ sudo LD_LIBRARY_PATH=/usr/local/lib/ zypper -vv --root $PWD/hello-world update 
Verbosity: 2
Initializing Target
Loading repository data...
Reading installed packages...
Force resolution: No

Nothing to do.
```

/cc @mlschroe as the author of the aforementioned workaround

**Comment by mrc0mmand** [comment] 2022-01-01 22:01
Also, to make OpenSUSE work with the latest mkosi GH Action as soon as possible, we could patch `libsolv` "on the fly" in https://github.com/systemd/mkosi/blob/main/action/setup-github-actions.sh until the issue is resolved in the `libsolv` upstream.

**Comment by evverx** [comment] 2022-01-01 22:15
@mrc0mmand wow that was quick :-) Thanks!

I think I kind of derailed the discussion about testing secure boot with the mkosi action started in https://github.com/systemd/systemd/pull/21960#issuecomment-1003587815. I actually was asking if you knew how to hook up secure boot to mkosi. Sorry about the confusion.

**Comment by DaanDeMeyer** [comment] 2022-01-04 15:12
I think we can close this

**Closed by DaanDeMeyer** 2022-01-04 15:12 UTC
