### ISSUE TITLE
LUKS + minimize errors with "blockdev: ioctl error"

### ISSUE THREAD

**Issue by brpatel12** [systemd/mkosi#1219] opened 2022-10-05 20:42 UTC
# Summary
`minimize=yes` doesn't work with LUKS encrypted images. This exact same build succeeds when minimize is set to no.

# mkosi.default
```bash
[Distribution]
Distribution=ubuntu
Release=focal
Repositories=main,universe
Architecture=x86_64

[Output]
Format=gpt_ext4
ManifestFormat=json
OutputDirectory=mkosi.output
Bootable=yes
BootProtocols=uefi
Encrypt=all
Minimize=yes

[Content]
WithNetwork=yes
CleanPackageMetadata=auto
BuildScript=mkosi_build.sh
InstallDirectory=mkosi.installdir
PostInstallationScript=mkosi_postinst.sh
FinalizeScript=mkosi_finalize.sh
```

# Error output
```bash
‣  Unmounting Package Cache
‣  Assigning hostname
‣  Copying in build script…
‣  Copying in sources…
‣  Copying in extra file trees…
‣  Mounting Package Cache
‣  Running postinstall script…

Skipping mkosi.postinst for build stage

‣  Unmounting Package Cache
‣  Running finalize script…

Skipping mkosi.finalize for build stage

‣  Unmounting image
‣  Creating ext4 root file system…
mke2fs 1.45.5 (07-Jan-2020)
Discarding device blocks: done                            
Creating filesystem with 6553600 4k blocks and 1638400 inodes
Filesystem UUID: 28b7dc78-5b60-4b9e-a303-33470ec91215
Superblock backups stored on blocks: 
	32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	4096000

Allocating group tables: done                            
Writing inode tables: done                            
Creating journal (32768 blocks): done
Copying files into the device: done
Writing superblocks and filesystem accounting information: done   

‣  Minimizing ext4 root file system…
resize2fs 1.45.5 (07-Jan-2020)
Resizing the filesystem on /home/brpatel/mkosi/mkosi.output/.mkosi-mkfs-ext4j6_ak5co to 4237600 (4k) blocks.
The filesystem on /home/brpatel/mkosi/mkosi.output/.mkosi-mkfs-ext4j6_ak5co is now 4237600 (4k) blocks long.

‣  Inserting generated root partition…
‣   Resizing disk image to 16.8G
‣   Inserting partition of 16.2G...
GPT PMBR size mismatch (1232895 != 35168255) will be corrected by write.
The backup GPT table is not on the end of the device. This problem will be corrected by write.
Disk /dev/loop6: 16.79 GiB, 18006147072 bytes, 35168256 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 2AA46081-E067-C44B-B485-A9171233F9B1

Old situation:

Device       Start     End Sectors  Size Type
/dev/loop6p1  2048 1230847 1228800  600M EFI System

>>> Script header accepted.
>>> Script header accepted.
>>> Created a new GPT disklabel (GUID: F1520D39-FF08-F84D-9E71-BE2E0910C093).
/dev/loop6p1: Created a new partition 1 of type 'EFI System' and of size 600 MiB.
Partition #1 contains a vfat signature.
/dev/loop6p2: Created a new partition 2 of type 'Linux root (x86-64)' and of size 16.2 GiB.
/dev/loop6p3: Done.

New situation:
Disklabel type: gpt
Disk identifier: F1520D39-FF08-F84D-9E71-BE2E0910C093

Device         Start      End  Sectors  Size Type
/dev/loop6p1    2048  1230847  1228800  600M EFI System
/dev/loop6p2 1230848 35166207 33935360 16.2G Linux root (x86-64)

The partition table has been altered.
blockdev: ioctl error on BLKRRPART: Device or resource busy
blockdev: ioctl error on BLKRRPART: Device or resource busy
‣   Writing partition...
‣    Setting up LUKS on image_name_test…
‣    Setting up LUKS on image_name_test…
blkdiscard: /dev/mapper/e7fa6100-e203-47fa-8922-da57e4f8a372: BLKDISCARD ioctl failed: Operation not supported
‣    (Closing LUKS on image_name_test)
‣  (Detaching /dev/loop6)
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/.local/lib/python3.8/site-packages/mkosi/__main__.py", line 36, in <module>
    main()
  File "/root/.local/lib/python3.8/site-packages/mkosi/__main__.py", line 27, in main
    run_verb(a)
  File "/root/.local/lib/python3.8/site-packages/mkosi/__init__.py", line 7932, in run_verb
    manifest = build_stuff(args)
  File "/root/.local/lib/python3.8/site-packages/mkosi/__init__.py", line 7297, in build_stuff
    image = build_image(args, root, do_run_build_script=True)
  File "/root/.local/lib/python3.8/site-packages/mkosi/__init__.py", line 7074, in build_image
    generated_root_part = insert_generated_root(args, raw, loopdev, generated_root, for_cache)
  File "/root/.local/lib/python3.8/site-packages/mkosi/__init__.py", line 3928, in insert_generated_root
    return insert_partition(
  File "/root/.local/lib/python3.8/site-packages/mkosi/__init__.py", line 3903, in insert_partition
    run(["blkdiscard", path])
  File "/root/.local/lib/python3.8/site-packages/mkosi/backend.py", line 733, in run
    return subprocess.run(cmdline, check=check, stdout=stdout, stderr=stderr, **kwargs)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['blkdiscard', '/dev/mapper/e7fa6100-e203-47fa-8922-da57e4f8a372']' returned non-zero exit status 1.
```

**Comment by brpatel12** [comment] 2022-10-10 19:24
Built on an Ubuntu 20.04 LTS machine (same as mkosi build image type).

**Comment by brpatel12** [comment] 2022-10-17 21:00
@behrmann any suggestions?

**Comment by behrmann** [comment] 2022-10-18 15:27
Sorry, forgot to answer: The question is not what distro did you build this on - although this is helpful as well -, but rather what is the FS on which you are building the image? 

If you have enough memory, you could try it on a tmpfs as well.

**Comment by brpatel12** [comment] 2022-10-18 15:41
- I believe the loopback devices are leftovers from old mkosi builds.
- I'm building from `/dev/sda2` which is `ext4`

```bash
brpatel@brpatel-hostname:~$ lsblk -a -o NAME,MOUNTPOINT,PARTTYPE,FSTYPE
NAME                       MOUNTPOINT                   PARTTYPE                             FSTYPE
loop0                      /snap/bare/5                                                      squashfs
loop1                      /snap/core20/1611                                                 squashfs
loop2                      /snap/gnome-3-38-2004/115                                         squashfs
loop3                                                                                        
├─loop3p1                                               c12a7328-f81f-11d2-ba4b-00a0c93ec93b vfat
└─loop3p2                                               4f68bce3-e8cd-4db1-96e7-fbcaf984b709 crypto_LUKS
  └─fb51f088-0153-40d9-a030-f0362fc83ca5
                                                                                             
loop4                      /snap/gtk-common-themes/1534                                      squashfs
loop5                      /snap/core18/2566                                                 squashfs
loop6                                                                                        
├─loop6p1                                               c12a7328-f81f-11d2-ba4b-00a0c93ec93b vfat
└─loop6p2                                               4f68bce3-e8cd-4db1-96e7-fbcaf984b709 crypto_LUKS
  └─22935636-b677-4c37-8f47-ffce4769c72f
                                                                                             ext4
loop7                      /snap/core18/2560                                                 squashfs
loop8                      /snap/gnome-3-34-1804/72                                          squashfs
loop9                      /snap/snap-store/592                                              squashfs
loop10                     /snap/core20/1623                                                 squashfs
loop11                     /snap/gtk-common-themes/1535                                      squashfs
loop12                     /snap/gnome-3-38-2004/119                                         squashfs
loop13                     /snap/snapd/16778                                                 squashfs
loop14                     /snap/gnome-3-34-1804/77                                          squashfs
loop15                     /snap/snap-store/599                                              squashfs
loop16                     /snap/snapd/17029                                                 squashfs
loop17                                                                                       
sda                                                                                          
├─sda1                     /boot/efi                    c12a7328-f81f-11d2-ba4b-00a0c93ec93b vfat
└─sda2                     /                            0fc63daf-8483-4772-8e79-3d69d8477de4 ext4
```

**Comment by brpatel12** [comment] 2022-10-18 15:58
> If you have enough memory, you could try it on a tmpfs as well.

Was there an explicit reason for this suggestion?

**Comment by behrmann** [comment] 2022-10-18 16:28
If you had had some outlandish FS you could have tried building on a tmpfs as the easiest solution to build anywhere else. 

As for the blkdiscard issues, no idea. Looks a bit similar to an error we had in CI here on Github, but I think that went away when we switched base to Ubuntu 22.04. I'd gather the issue is somewhere in Ubuntu's stack.

**Comment by DaanDeMeyer** [comment] 2022-10-27 09:42
This will probably be fixed when we move to systemd-repart. I don't think anyone's going to hack on fixing this in mkosi's current partition/blockdev handling

**Comment by DaanDeMeyer** [comment] 2023-02-14 15:13
This should be fixed now that we moved to systemd-repart, let us know if it isn't and we'll reopen the issue

**Closed by DaanDeMeyer** 2023-02-14 15:13 UTC
Labels: bug
