### ISSUE TITLE
mkosi deletes files too broadly in output-dir

### ISSUE THREAD

**Issue by dvzrv** [systemd/mkosi#1886] opened 2023-09-08 09:57 UTC
When running `mkosi build` for a project with name `$name` and an output directory `$output_dir`, the process removes files from the output directory too broadly.

E.g. a directory or file named `$output_dir/${name}_foo` will be deleted when running `mkosi build`.

It would be better if mkosi tracked its artifacts and only deleted those that belong/ are created by a particular project.

**Comment by DaanDeMeyer** [comment] 2024-04-14 13:53
This should be fixed now, as we only delete stuff we know about, the rest if left to clean scripts.

**Closed by DaanDeMeyer** 2024-04-14 13:53 UTC
Labels: RFE

**Comment by septatrix** [comment] 2024-04-26 00:45
As a result of the changes mkosi is no longer aware of the files generated when using `SplitArtifacts=yes`. I am not sure if this was intended. After all the output is something generated by mkosi and not by user so it seems like a fair assumption that one should not have to write a cleanup script to remove those files (and they pile up quickly if the UUID is part of the `SplitName=`).

**Comment by DaanDeMeyer** [comment] 2024-04-26 06:33
@septatrix We need to be able to derive the files at the time we run clean. I haven't looked yet whether I can query the list of split partitions from repart easily at that point. e.g. we can't use the tools tree yet and such. So for now, please use a clean script to get rid of split artifacts.

**Comment by DaanDeMeyer** [comment] 2024-04-26 08:44
@septatrix This would need to be independent of the cache, probably in the manifest but the manifest can be disabled so it might not be there either. So we'd have to either make the manifest required again or add a new state file to store which outputs we generated, which I would prefer to avoid. Clean scripts allow for a way to handle this without having to introduce more state.

**Comment by septatrix** [comment] 2024-04-26 19:35
Yeah, it is likely not worth the effort. I am currently using:

```sh
#!/usr/bin/env sh

set -eux

# Remove any files generated when running with 'SplitArtifacts=yes'
rm -- "$OUTPUTDIR"/"$IMAGE_ID"_"$IMAGE_VERSION"._*.*.raw*
```

which works with my `SplitName=_%U.%t` (yeah the underscore is ugly but that is due to limitations in sysupdate and repart :/)

PS: I noticed that `$IMAGE_ID` and `$IMAGE_VERSION` are not documented in the env table
