### ISSUE TITLE
Support iso9660 as output format

### ISSUE THREAD

**Issue by behrmann** [systemd/mkosi#1220] opened 2022-10-06 09:56 UTC
Somebody asked for it at the summit.

**Comment by DaanDeMeyer** [comment] 2023-06-30 09:18
So I looked into how this would work. There's actually 2 parts to this, supporting the actual ISO9660 filesystem as a filesystem for partitions and being able to boot from a CD-ROM.

To boot UEFI from a CD-ROM, you need to put a EFI boot catalog entry in the ISO filesystem (El Torito) that points to the ESP partition. The ISO filesystem itself needs to start at offset 32k in the image. Note that the ISO filesystem itself doesn't need to actually contain any files to allow booting from a CD-ROM, you just need the El Torito boot record in the EFI filesystem.

So to make the booting from CD-ROM work, we'd need to add support to systemd-repart to add `Format=iso` for partitions and probably add an easy way to have a partition start at a very specific offset so we can have the iso partition start at offset 32k. We'll also need to add a way to configure boot catalog entries for the iso filesystem to systemd-repart, which should be implemented as generic infra so we can specify filesystem options for any supported filesystem, probably via an `[ISO]` section in the partition definition file or so (and similarly, `[Btrfs]`, `[XFS]` and so).

Populating an iso filesytem is more or less like populating a regular iso filesystem, but will also require adding the iso filesystem support to systemd-repart.

**Comment by DaanDeMeyer** [comment] 2023-08-11 12:44
So I think this is something to support in repart so I opened an issue in the system repository: https://github.com/systemd/systemd/issues/28798. Let's close this here

**Closed by DaanDeMeyer** 2023-08-11 12:44 UTC
Labels: RFE

**Comment by adrelanos** [comment] 2023-12-21 14:36
Reasons of ISO support:

* most Linux distributions support downloadable ISO based installers which then run calamares or similar
* having a Live ISO
* it's what users know and are accustomed to
* tool that know how to write to DVD or USB understand ISOs
* bootable in virtualizers such as VirtualBox

But as mentioned in https://github.com/systemd/systemd/issues/28798 it does not necessarily need to be ISO9660. Any bootable image format that is DVD compatible would be nice.

I don't understand yet why adding this feature to repart makes this work for mkosi but I trust you're right.

This might be a duplicate of:

* https://github.com/systemd/mkosi/issues/520
