### ISSUE TITLE
Ubuntu 17.10 Incorrect Debootstrap Script

### ISSUE THREAD

**Issue by willronchetti** [systemd/mkosi#129] opened 2017-07-21 14:45 UTC
Building on #84, to get around the '--merged-usr' option I've upgraded Ubuntu to 17.10.
 
However, 

- Upgrading to 17.10 allows mkosi to proceed beyond the '--merged-usr' problem, but fails out later looking for the script /usr/share/debootstrap/scripts/"17.10" when I believe it should be looking for /usr/share/debootstrap/scripts/artful
- Adding a symlink to bypass the "17.10" problem leads to mkosi querying 'http://archive.ubuntu.com/ubuntu/dists/"17.10"/Release' for the release file, which is obviously wrong, it should query 'http://archive.ubuntu.com/ubuntu/dists/artful/Release'.

Mkosi simply needs to find the proper script, and I believe this should work.

To reproduce, simply run 'mkosi' on Ubuntu 17.10.

**Comment by fsateler** [comment] 2017-07-21 23:10
This is a duplicate of #82

**Closed** 2017-07-24 07:40 UTC
