### ISSUE TITLE
host networking in nspawn containers not working with recent versions of mkosi

### ISSUE THREAD

**Issue by smpsnr** [systemd/mkosi#908] opened 2022-02-18 00:55 UTC
I'd like to use mkosi to quickly build nspawn containers to test various servers on localhost. For instance see [this configuration](https://github.com/DWeb-Deconstruction-Project/synapse-nspawn) I wrote for the synapse matrix server. 

For this use case I don't need the container to have a private network. I used to set `VirtualEthernet=no` in my `.nspawn` configuration and everything just worked.

However, as of recent versions running `mkosi` with the same configuration files will produce a container that fails to start `systemd-resolved`. In the container `/etc/resolv.conf` links to `/run/systemd/resolve/resolv.conf`, which does not exist.

**How to reproduce:** build a Debian image with mkosi pinned to [this commit](https://github.com/systemd/mkosi/commits/f9b565e11a7310d69c314f12d4c8d173e3196812) and then build one with the latest version. 

`mkosi.default`
```
[Distribution]
Distribution=debian
Release=bullseye

[Output]
Format=gpt_ext4
Output=/var/lib/machines/test.raw

[Packages]
NSpawnSettings=test.nspawn
Cache=/var/cache/mkosi

[Validation]
Autologin=yes
```

`test.nspawn`
```
[Exec]
Boot=yes
PrivateUsers=yes

[Network]
VirtualEthernet=no
```
- `sudo -E python3 -m mkosi`
- `sudo systemd-nspawn --machine test --settings trusted`

With older versions this would boot with host networking, with recent versions it'll still boot but `systemd-resolved` will fail to start:
```
[FAILED] Failed to start Network Name Resolution.
See 'systemctl status systemd-resolved.service' for details.
```
```
root@test:~# systemctl status systemd-resolved.service
● systemd-resolved.service - Network Name Resolution
     Loaded: loaded (/lib/systemd/system/systemd-resolved.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2022-02-17 17:42:44 PST; 8s ago
       Docs: man:systemd-resolved.service(8)
             man:org.freedesktop.resolve1(5)
             https://www.freedesktop.org/wiki/Software/systemd/writing-network-configuration-managers
             https://www.freedesktop.org/wiki/Software/systemd/writing-resolver-clients
    Process: 40 ExecStart=/lib/systemd/systemd-resolved (code=exited, status=1/FAILURE)
   Main PID: 40 (code=exited, status=1/FAILURE)
      Error: 13 (Permission denied)

Feb 17 17:42:44 test systemd[1]: systemd-resolved.service: Scheduled restart job, restart counter is at 5.
Feb 17 17:42:44 test systemd[1]: Stopped Network Name Resolution.
Feb 17 17:42:44 test systemd[1]: systemd-resolved.service: Start reques
t repeated too quickly.
Feb 17 17:42:44 test systemd[1]: systemd-resolved.service: Failed with 
result 'exit-code'.
Feb 17 17:42:44 test systemd[1]: Failed to start Network Name Resolution.
```

`/etc/resolv.conf` is linked to `/run/systemd/resolve/resolv.conf`...
```
root@test:~# ls -l /etc/resolv.conf 
lrwxrwxrwx 1 root root 34 Feb 17 17:42 /etc/resolv.conf -> ../run/systemd/resolve/resolv.conf
```
... but `/run/systemd/resolve/resolv.conf` does not exist:
```
root@test:~# ls -l /run/systemd/resolve/resolv.conf
ls: cannot access '/run/systemd/resolve/resolv.conf': No such file or directory
```

**Comment by Edu4rdSHL** [comment] 2022-04-15 01:04
You probably need to add the `CAP_NET_ADMIN` to your container configuration, the `Error: 13 (Permission denied)` is clearly not a mkosi problem but probably your OS security policies are doing that.

**Comment by DaanDeMeyer** [comment] 2022-06-16 20:21
mkosi doesn't do anything in particular to stop or enable systemd-resolved from working in nspawn. If you're not using private networking and want DNS resolution in the container, the first thing to consider is that you probably don't want to run systemd-resolved in the container, as it will conflict with systemd-resolved on the host if it's running there since they'll both try to use the same port.

If you have any software that relies on /etc/resolv.conf in the container though (which could also be resolved running in the container), you can use systemd-nspawn's --resolv-conf option to configure how the /etc/resolv.conf from the host is brought into the container.

Regardless, this isn't really a mkosi issue, so closing here.

**Closed by DaanDeMeyer** 2022-06-16 20:21 UTC

**Comment by septatrix** [comment] 2023-10-25 21:54
Just sharing my findings while trying to switch from a Debian base to a Fedora base: For Fedora the problem is that its `/etc/nsswitch.conf` contained the following:

```txt
hosts:      files myhostname resolve [!UNAVAIL=return] dns
```

However, inside an nspawn container this leads to the observed behaviour as systemd-resolved still starts so it is available, leading to the status check `!UNAVAIL` to succeed and thus the chain to return before falling back to the "normal" DNS option. Sadly, modifying `nsswitch.conf` is a real PITA as it is automatically generated by `authselect` which is just as annoying to extend as it does not support any kind of overrides or `conf.d` directories.

An alternative would be to add a drop-in file for resolved to prevent it from starting inside containers. For my part I choose to completely overwrite the `authselect`/`nsswitch.conf` profile as that was the behaviour under Debian.
